-- Modify "tender_documents" table
ALTER TABLE "tender_documents" ADD COLUMN "kind" character varying NOT NULL DEFAULT 'supporting', ADD COLUMN "version" bigint NOT NULL DEFAULT 0;
-- Modify "tenders" table
ALTER TABLE "tenders" ADD COLUMN "decision" character varying NULL, ADD COLUMN "decision_rationale" text NULL, ADD COLUMN "decided_by" uuid NULL, ADD COLUMN "decided_at" timestamptz NULL, ADD COLUMN "outcome" jsonb NULL, ADD COLUMN "status_history" jsonb NULL, ADD COLUMN "final_document_version" bigint NOT NULL DEFAULT 0, ADD COLUMN "ready_for_submission" boolean NOT NULL DEFAULT false;
-- Create "tender_sections" table
CREATE TABLE "tender_sections" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "title" character varying NOT NULL, "description" text NULL, "assignee_id" uuid NULL, "reviewer_id" uuid NULL, "due_date" timestamptz NULL, "status" character varying NOT NULL DEFAULT 'not_started', "document_url" character varying NULL, "review_comments" text NULL, "sort_order" bigint NOT NULL DEFAULT 0, "submitted_at" timestamptz NULL, "reviewed_by" uuid NULL, "reviewed_at" timestamptz NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "tender_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "tender_sections_tenders_sections" FOREIGN KEY ("tender_id") REFERENCES "tenders" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "tendersection_tenant_id_tender_id" to table: "tender_sections"
CREATE INDEX "tendersection_tenant_id_tender_id" ON "tender_sections" ("tenant_id", "tender_id");
-- Create "tender_submissions" table
CREATE TABLE "tender_submissions" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "method" character varying NOT NULL, "submitted_at" timestamptz NOT NULL, "submitted_by" uuid NOT NULL, "recipient_email" character varying NULL, "email_subject" character varying NULL, "email_body" text NULL, "document_url" character varying NULL, "courier" character varying NULL, "tracking_number" character varying NULL, "address" text NULL, "proof_url" character varying NULL, "confirmation_number" character varying NULL, "delivery_status" character varying NOT NULL DEFAULT 'recorded', "notes" text NULL, "created_at" timestamptz NOT NULL, "tender_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "tender_submissions_tenders_submissions" FOREIGN KEY ("tender_id") REFERENCES "tenders" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "tendersubmission_tenant_id_tender_id" to table: "tender_submissions"
CREATE INDEX "tendersubmission_tenant_id_tender_id" ON "tender_submissions" ("tenant_id", "tender_id");
