-- Create "outbox_events" table
CREATE TABLE "outbox_events" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "aggregate_type" character varying NOT NULL, "aggregate_id" uuid NOT NULL, "event_type" character varying NOT NULL, "payload" jsonb NULL, "status" character varying NOT NULL DEFAULT 'pending', "attempts" bigint NOT NULL DEFAULT 0, "last_attempt_at" timestamptz NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create "tenant_sync_events" table
CREATE TABLE "tenant_sync_events" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "tenant_slug" character varying NOT NULL, "source_service" character varying NOT NULL, "payload" jsonb NULL, "synced_at" timestamptz NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', PRIMARY KEY ("id"));
-- Create "projects" table
CREATE TABLE "projects" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "name" character varying NOT NULL, "description" character varying NULL, "status" character varying NOT NULL DEFAULT 'active', "start_date" timestamptz NULL, "end_date" timestamptz NULL, "budget" double precision NULL, "currency" character varying NOT NULL DEFAULT 'USD', "owner_id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "metadata" jsonb NULL, PRIMARY KEY ("id"));
-- Create "tasks" table
CREATE TABLE "tasks" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "title" character varying NOT NULL, "description" character varying NULL, "status" character varying NOT NULL DEFAULT 'todo', "priority" character varying NOT NULL DEFAULT 'medium', "assignee_id" uuid NULL, "due_date" timestamptz NULL, "completed_at" timestamptz NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "metadata" jsonb NULL, "project_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "tasks_projects_tasks" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "activities" table
CREATE TABLE "activities" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "user_id" uuid NOT NULL, "activity_type" character varying NOT NULL, "payload" jsonb NULL, "occurred_at" timestamptz NOT NULL, "project_id" uuid NULL, "task_id" uuid NULL, PRIMARY KEY ("id"), CONSTRAINT "activities_projects_activities" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "activities_tasks_activities" FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create "attachments" table
CREATE TABLE "attachments" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "file_url" character varying NOT NULL, "file_name" character varying NOT NULL, "file_size" bigint NOT NULL, "mime_type" character varying NULL, "uploaded_by" uuid NOT NULL, "uploaded_at" timestamptz NOT NULL, "metadata" jsonb NULL, "project_id" uuid NULL, "task_id" uuid NULL, PRIMARY KEY ("id"), CONSTRAINT "attachments_projects_attachments" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "attachments_tasks_attachments" FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create "comments" table
CREATE TABLE "comments" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "user_id" uuid NOT NULL, "content" text NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "metadata" jsonb NULL, "project_id" uuid NULL, "task_id" uuid NULL, PRIMARY KEY ("id"), CONSTRAINT "comments_projects_comments" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "comments_tasks_comments" FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create "milestones" table
CREATE TABLE "milestones" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "name" character varying NOT NULL, "description" character varying NULL, "target_date" timestamptz NULL, "status" character varying NOT NULL DEFAULT 'pending', "completed_at" timestamptz NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "project_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "milestones_projects_milestones" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "project_members" table
CREATE TABLE "project_members" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "user_id" uuid NOT NULL, "role_code" character varying NOT NULL, "joined_at" timestamptz NOT NULL, "left_at" timestamptz NULL, "metadata" jsonb NULL, "project_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "project_members_projects_members" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "permissions" table
CREATE TABLE "permissions" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "name" character varying NOT NULL, "module" character varying NOT NULL, "action" character varying NOT NULL, "resource" character varying NULL, "description" character varying NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create "roles" table
CREATE TABLE "roles" ("code" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NULL, "is_system" boolean NOT NULL DEFAULT false, "permissions" jsonb NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("code"));
-- Create "role_permissions" table
CREATE TABLE "role_permissions" ("id" uuid NOT NULL, "assigned_at" timestamptz NOT NULL, "permission_id" uuid NOT NULL, "role_code" character varying NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "role_permissions_permissions_role_permissions" FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "role_permissions_roles_role_permissions" FOREIGN KEY ("role_code") REFERENCES "roles" ("code") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "task_dependencies" table
CREATE TABLE "task_dependencies" ("id" uuid NOT NULL, "depends_on_task_id" uuid NOT NULL, "dependency_type" character varying NOT NULL DEFAULT 'blocks', "created_at" timestamptz NOT NULL, "task_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "task_dependencies_tasks_dependencies" FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "user_roles" table
CREATE TABLE "user_roles" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "user_id" uuid NOT NULL, "assigned_at" timestamptz NOT NULL, "assigned_by" uuid NULL, "metadata" jsonb NULL, "role_code" character varying NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "user_roles_roles_user_roles" FOREIGN KEY ("role_code") REFERENCES "roles" ("code") ON UPDATE NO ACTION ON DELETE NO ACTION);
