// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/projects-service/internal/ent/activity"
	"github.com/bengobox/projects-service/internal/ent/project"
	"github.com/bengobox/projects-service/internal/ent/task"
	"github.com/google/uuid"
)

// ActivityCreate is the builder for creating a Activity entity.
type ActivityCreate struct {
	config
	mutation *ActivityMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (ac *ActivityCreate) SetTenantID(u uuid.UUID) *ActivityCreate {
	ac.mutation.SetTenantID(u)
	return ac
}

// SetProjectID sets the "project_id" field.
func (ac *ActivityCreate) SetProjectID(u uuid.UUID) *ActivityCreate {
	ac.mutation.SetProjectID(u)
	return ac
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (ac *ActivityCreate) SetNillableProjectID(u *uuid.UUID) *ActivityCreate {
	if u != nil {
		ac.SetProjectID(*u)
	}
	return ac
}

// SetTaskID sets the "task_id" field.
func (ac *ActivityCreate) SetTaskID(u uuid.UUID) *ActivityCreate {
	ac.mutation.SetTaskID(u)
	return ac
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (ac *ActivityCreate) SetNillableTaskID(u *uuid.UUID) *ActivityCreate {
	if u != nil {
		ac.SetTaskID(*u)
	}
	return ac
}

// SetUserID sets the "user_id" field.
func (ac *ActivityCreate) SetUserID(u uuid.UUID) *ActivityCreate {
	ac.mutation.SetUserID(u)
	return ac
}

// SetActivityType sets the "activity_type" field.
func (ac *ActivityCreate) SetActivityType(s string) *ActivityCreate {
	ac.mutation.SetActivityType(s)
	return ac
}

// SetPayload sets the "payload" field.
func (ac *ActivityCreate) SetPayload(m map[string]interface{}) *ActivityCreate {
	ac.mutation.SetPayload(m)
	return ac
}

// SetOccurredAt sets the "occurred_at" field.
func (ac *ActivityCreate) SetOccurredAt(t time.Time) *ActivityCreate {
	ac.mutation.SetOccurredAt(t)
	return ac
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (ac *ActivityCreate) SetNillableOccurredAt(t *time.Time) *ActivityCreate {
	if t != nil {
		ac.SetOccurredAt(*t)
	}
	return ac
}

// SetID sets the "id" field.
func (ac *ActivityCreate) SetID(u uuid.UUID) *ActivityCreate {
	ac.mutation.SetID(u)
	return ac
}

// SetNillableID sets the "id" field if the given value is not nil.
func (ac *ActivityCreate) SetNillableID(u *uuid.UUID) *ActivityCreate {
	if u != nil {
		ac.SetID(*u)
	}
	return ac
}

// SetProject sets the "project" edge to the Project entity.
func (ac *ActivityCreate) SetProject(p *Project) *ActivityCreate {
	return ac.SetProjectID(p.ID)
}

// SetTask sets the "task" edge to the Task entity.
func (ac *ActivityCreate) SetTask(t *Task) *ActivityCreate {
	return ac.SetTaskID(t.ID)
}

// Mutation returns the ActivityMutation object of the builder.
func (ac *ActivityCreate) Mutation() *ActivityMutation {
	return ac.mutation
}

// Save creates the Activity in the database.
func (ac *ActivityCreate) Save(ctx context.Context) (*Activity, error) {
	ac.defaults()
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *ActivityCreate) SaveX(ctx context.Context) *Activity {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *ActivityCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *ActivityCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *ActivityCreate) defaults() {
	if _, ok := ac.mutation.OccurredAt(); !ok {
		v := activity.DefaultOccurredAt()
		ac.mutation.SetOccurredAt(v)
	}
	if _, ok := ac.mutation.ID(); !ok {
		v := activity.DefaultID()
		ac.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *ActivityCreate) check() error {
	if _, ok := ac.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Activity.tenant_id"`)}
	}
	if _, ok := ac.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Activity.user_id"`)}
	}
	if _, ok := ac.mutation.ActivityType(); !ok {
		return &ValidationError{Name: "activity_type", err: errors.New(`ent: missing required field "Activity.activity_type"`)}
	}
	if v, ok := ac.mutation.ActivityType(); ok {
		if err := activity.ActivityTypeValidator(v); err != nil {
			return &ValidationError{Name: "activity_type", err: fmt.Errorf(`ent: validator failed for field "Activity.activity_type": %w`, err)}
		}
	}
	if _, ok := ac.mutation.OccurredAt(); !ok {
		return &ValidationError{Name: "occurred_at", err: errors.New(`ent: missing required field "Activity.occurred_at"`)}
	}
	return nil
}

func (ac *ActivityCreate) sqlSave(ctx context.Context) (*Activity, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *ActivityCreate) createSpec() (*Activity, *sqlgraph.CreateSpec) {
	var (
		_node = &Activity{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(activity.Table, sqlgraph.NewFieldSpec(activity.FieldID, field.TypeUUID))
	)
	if id, ok := ac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := ac.mutation.TenantID(); ok {
		_spec.SetField(activity.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := ac.mutation.UserID(); ok {
		_spec.SetField(activity.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := ac.mutation.ActivityType(); ok {
		_spec.SetField(activity.FieldActivityType, field.TypeString, value)
		_node.ActivityType = value
	}
	if value, ok := ac.mutation.Payload(); ok {
		_spec.SetField(activity.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := ac.mutation.OccurredAt(); ok {
		_spec.SetField(activity.FieldOccurredAt, field.TypeTime, value)
		_node.OccurredAt = value
	}
	if nodes := ac.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activity.ProjectTable,
			Columns: []string{activity.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activity.TaskTable,
			Columns: []string{activity.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ActivityCreateBulk is the builder for creating many Activity entities in bulk.
type ActivityCreateBulk struct {
	config
	err      error
	builders []*ActivityCreate
}

// Save creates the Activity entities in the database.
func (acb *ActivityCreateBulk) Save(ctx context.Context) ([]*Activity, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Activity, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ActivityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *ActivityCreateBulk) SaveX(ctx context.Context) []*Activity {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *ActivityCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *ActivityCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
