// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/projects-service/internal/ent/budget"
	"github.com/bengobox/projects-service/internal/ent/project"
	"github.com/google/uuid"
)

// Budget is the model entity for the Budget schema.
type Budget struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID uuid.UUID `json:"project_id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// TotalAmount holds the value of the "total_amount" field.
	TotalAmount float64 `json:"total_amount,omitempty"`
	// SpentAmount holds the value of the "spent_amount" field.
	SpentAmount float64 `json:"spent_amount,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BudgetQuery when eager-loading is set.
	Edges        BudgetEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BudgetEdges holds the relations/edges for other nodes in the graph.
type BudgetEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Expenses holds the value of the expenses edge.
	Expenses []*Expense `json:"expenses,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BudgetEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// ExpensesOrErr returns the Expenses value or an error if the edge
// was not loaded in eager-loading.
func (e BudgetEdges) ExpensesOrErr() ([]*Expense, error) {
	if e.loadedTypes[1] {
		return e.Expenses, nil
	}
	return nil, &NotLoadedError{edge: "expenses"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Budget) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case budget.FieldTotalAmount, budget.FieldSpentAmount:
			values[i] = new(sql.NullFloat64)
		case budget.FieldCurrency, budget.FieldStatus:
			values[i] = new(sql.NullString)
		case budget.FieldCreatedAt, budget.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case budget.FieldID, budget.FieldProjectID, budget.FieldTenantID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Budget fields.
func (b *Budget) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case budget.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				b.ID = *value
			}
		case budget.FieldProjectID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value != nil {
				b.ProjectID = *value
			}
		case budget.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				b.TenantID = *value
			}
		case budget.FieldTotalAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_amount", values[i])
			} else if value.Valid {
				b.TotalAmount = value.Float64
			}
		case budget.FieldSpentAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field spent_amount", values[i])
			} else if value.Valid {
				b.SpentAmount = value.Float64
			}
		case budget.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				b.Currency = value.String
			}
		case budget.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				b.Status = value.String
			}
		case budget.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				b.CreatedAt = value.Time
			}
		case budget.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				b.UpdatedAt = value.Time
			}
		default:
			b.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Budget.
// This includes values selected through modifiers, order, etc.
func (b *Budget) Value(name string) (ent.Value, error) {
	return b.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the Budget entity.
func (b *Budget) QueryProject() *ProjectQuery {
	return NewBudgetClient(b.config).QueryProject(b)
}

// QueryExpenses queries the "expenses" edge of the Budget entity.
func (b *Budget) QueryExpenses() *ExpenseQuery {
	return NewBudgetClient(b.config).QueryExpenses(b)
}

// Update returns a builder for updating this Budget.
// Note that you need to call Budget.Unwrap() before calling this method if this Budget
// was returned from a transaction, and the transaction was committed or rolled back.
func (b *Budget) Update() *BudgetUpdateOne {
	return NewBudgetClient(b.config).UpdateOne(b)
}

// Unwrap unwraps the Budget entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (b *Budget) Unwrap() *Budget {
	_tx, ok := b.config.driver.(*txDriver)
	if !ok {
		panic("ent: Budget is not a transactional entity")
	}
	b.config.driver = _tx.drv
	return b
}

// String implements the fmt.Stringer.
func (b *Budget) String() string {
	var builder strings.Builder
	builder.WriteString("Budget(")
	builder.WriteString(fmt.Sprintf("id=%v, ", b.ID))
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", b.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", b.TenantID))
	builder.WriteString(", ")
	builder.WriteString("total_amount=")
	builder.WriteString(fmt.Sprintf("%v", b.TotalAmount))
	builder.WriteString(", ")
	builder.WriteString("spent_amount=")
	builder.WriteString(fmt.Sprintf("%v", b.SpentAmount))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(b.Currency)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(b.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(b.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(b.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Budgets is a parsable slice of Budget.
type Budgets []*Budget
