// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/projects-service/internal/ent/budget"
	"github.com/bengobox/projects-service/internal/ent/expense"
	"github.com/google/uuid"
)

// Expense is the model entity for the Expense schema.
type Expense struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// BudgetID holds the value of the "budget_id" field.
	BudgetID uuid.UUID `json:"budget_id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID uuid.UUID `json:"project_id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// Category holds the value of the "category" field.
	Category string `json:"category,omitempty"`
	// IncurredBy holds the value of the "incurred_by" field.
	IncurredBy uuid.UUID `json:"incurred_by,omitempty"`
	// IncurredAt holds the value of the "incurred_at" field.
	IncurredAt time.Time `json:"incurred_at,omitempty"`
	// ReceiptURL holds the value of the "receipt_url" field.
	ReceiptURL string `json:"receipt_url,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ExpenseQuery when eager-loading is set.
	Edges        ExpenseEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ExpenseEdges holds the relations/edges for other nodes in the graph.
type ExpenseEdges struct {
	// Budget holds the value of the budget edge.
	Budget *Budget `json:"budget,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// BudgetOrErr returns the Budget value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ExpenseEdges) BudgetOrErr() (*Budget, error) {
	if e.Budget != nil {
		return e.Budget, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: budget.Label}
	}
	return nil, &NotLoadedError{edge: "budget"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Expense) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case expense.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case expense.FieldDescription, expense.FieldCurrency, expense.FieldCategory, expense.FieldReceiptURL, expense.FieldStatus:
			values[i] = new(sql.NullString)
		case expense.FieldIncurredAt, expense.FieldCreatedAt, expense.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case expense.FieldID, expense.FieldBudgetID, expense.FieldProjectID, expense.FieldTenantID, expense.FieldIncurredBy:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Expense fields.
func (e *Expense) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case expense.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				e.ID = *value
			}
		case expense.FieldBudgetID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field budget_id", values[i])
			} else if value != nil {
				e.BudgetID = *value
			}
		case expense.FieldProjectID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value != nil {
				e.ProjectID = *value
			}
		case expense.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				e.TenantID = *value
			}
		case expense.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				e.Description = value.String
			}
		case expense.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				e.Amount = value.Float64
			}
		case expense.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				e.Currency = value.String
			}
		case expense.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				e.Category = value.String
			}
		case expense.FieldIncurredBy:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field incurred_by", values[i])
			} else if value != nil {
				e.IncurredBy = *value
			}
		case expense.FieldIncurredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field incurred_at", values[i])
			} else if value.Valid {
				e.IncurredAt = value.Time
			}
		case expense.FieldReceiptURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field receipt_url", values[i])
			} else if value.Valid {
				e.ReceiptURL = value.String
			}
		case expense.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				e.Status = value.String
			}
		case expense.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				e.CreatedAt = value.Time
			}
		case expense.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				e.UpdatedAt = value.Time
			}
		default:
			e.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Expense.
// This includes values selected through modifiers, order, etc.
func (e *Expense) Value(name string) (ent.Value, error) {
	return e.selectValues.Get(name)
}

// QueryBudget queries the "budget" edge of the Expense entity.
func (e *Expense) QueryBudget() *BudgetQuery {
	return NewExpenseClient(e.config).QueryBudget(e)
}

// Update returns a builder for updating this Expense.
// Note that you need to call Expense.Unwrap() before calling this method if this Expense
// was returned from a transaction, and the transaction was committed or rolled back.
func (e *Expense) Update() *ExpenseUpdateOne {
	return NewExpenseClient(e.config).UpdateOne(e)
}

// Unwrap unwraps the Expense entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (e *Expense) Unwrap() *Expense {
	_tx, ok := e.config.driver.(*txDriver)
	if !ok {
		panic("ent: Expense is not a transactional entity")
	}
	e.config.driver = _tx.drv
	return e
}

// String implements the fmt.Stringer.
func (e *Expense) String() string {
	var builder strings.Builder
	builder.WriteString("Expense(")
	builder.WriteString(fmt.Sprintf("id=%v, ", e.ID))
	builder.WriteString("budget_id=")
	builder.WriteString(fmt.Sprintf("%v", e.BudgetID))
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", e.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", e.TenantID))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(e.Description)
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", e.Amount))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(e.Currency)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(e.Category)
	builder.WriteString(", ")
	builder.WriteString("incurred_by=")
	builder.WriteString(fmt.Sprintf("%v", e.IncurredBy))
	builder.WriteString(", ")
	builder.WriteString("incurred_at=")
	builder.WriteString(e.IncurredAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("receipt_url=")
	builder.WriteString(e.ReceiptURL)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(e.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(e.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(e.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Expenses is a parsable slice of Expense.
type Expenses []*Expense
