// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/projects-service/internal/ent/milestone"
	"github.com/bengobox/projects-service/internal/ent/project"
	"github.com/google/uuid"
)

// MilestoneCreate is the builder for creating a Milestone entity.
type MilestoneCreate struct {
	config
	mutation *MilestoneMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *MilestoneCreate) SetTenantID(v uuid.UUID) *MilestoneCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *MilestoneCreate) SetProjectID(v uuid.UUID) *MilestoneCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *MilestoneCreate) SetName(v string) *MilestoneCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *MilestoneCreate) SetDescription(v string) *MilestoneCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *MilestoneCreate) SetNillableDescription(v *string) *MilestoneCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetTargetDate sets the "target_date" field.
func (_c *MilestoneCreate) SetTargetDate(v time.Time) *MilestoneCreate {
	_c.mutation.SetTargetDate(v)
	return _c
}

// SetNillableTargetDate sets the "target_date" field if the given value is not nil.
func (_c *MilestoneCreate) SetNillableTargetDate(v *time.Time) *MilestoneCreate {
	if v != nil {
		_c.SetTargetDate(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *MilestoneCreate) SetStatus(v string) *MilestoneCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MilestoneCreate) SetNillableStatus(v *string) *MilestoneCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *MilestoneCreate) SetCompletedAt(v time.Time) *MilestoneCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *MilestoneCreate) SetNillableCompletedAt(v *time.Time) *MilestoneCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MilestoneCreate) SetCreatedAt(v time.Time) *MilestoneCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MilestoneCreate) SetNillableCreatedAt(v *time.Time) *MilestoneCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MilestoneCreate) SetUpdatedAt(v time.Time) *MilestoneCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MilestoneCreate) SetNillableUpdatedAt(v *time.Time) *MilestoneCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MilestoneCreate) SetID(v uuid.UUID) *MilestoneCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MilestoneCreate) SetNillableID(v *uuid.UUID) *MilestoneCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *MilestoneCreate) SetProject(v *Project) *MilestoneCreate {
	return _c.SetProjectID(v.ID)
}

// Mutation returns the MilestoneMutation object of the builder.
func (_c *MilestoneCreate) Mutation() *MilestoneMutation {
	return _c.mutation
}

// Save creates the Milestone in the database.
func (_c *MilestoneCreate) Save(ctx context.Context) (*Milestone, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MilestoneCreate) SaveX(ctx context.Context) *Milestone {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MilestoneCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MilestoneCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MilestoneCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := milestone.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := milestone.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := milestone.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := milestone.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MilestoneCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Milestone.tenant_id"`)}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "Milestone.project_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Milestone.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := milestone.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Milestone.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Milestone.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Milestone.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Milestone.updated_at"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "Milestone.project"`)}
	}
	return nil
}

func (_c *MilestoneCreate) sqlSave(ctx context.Context) (*Milestone, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MilestoneCreate) createSpec() (*Milestone, *sqlgraph.CreateSpec) {
	var (
		_node = &Milestone{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(milestone.Table, sqlgraph.NewFieldSpec(milestone.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(milestone.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(milestone.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(milestone.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.TargetDate(); ok {
		_spec.SetField(milestone.FieldTargetDate, field.TypeTime, value)
		_node.TargetDate = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(milestone.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(milestone.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(milestone.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(milestone.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   milestone.ProjectTable,
			Columns: []string{milestone.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MilestoneCreateBulk is the builder for creating many Milestone entities in bulk.
type MilestoneCreateBulk struct {
	config
	err      error
	builders []*MilestoneCreate
}

// Save creates the Milestone entities in the database.
func (_c *MilestoneCreateBulk) Save(ctx context.Context) ([]*Milestone, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Milestone, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MilestoneMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MilestoneCreateBulk) SaveX(ctx context.Context) []*Milestone {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MilestoneCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MilestoneCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
