// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/projects-service/internal/ent/project"
	"github.com/bengobox/projects-service/internal/ent/projectmember"
	"github.com/google/uuid"
)

// ProjectMember is the model entity for the ProjectMember schema.
type ProjectMember struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID uuid.UUID `json:"project_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// RoleCode holds the value of the "role_code" field.
	RoleCode string `json:"role_code,omitempty"`
	// JoinedAt holds the value of the "joined_at" field.
	JoinedAt time.Time `json:"joined_at,omitempty"`
	// LeftAt holds the value of the "left_at" field.
	LeftAt time.Time `json:"left_at,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProjectMemberQuery when eager-loading is set.
	Edges        ProjectMemberEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProjectMemberEdges holds the relations/edges for other nodes in the graph.
type ProjectMemberEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectMemberEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProjectMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case projectmember.FieldMetadata:
			values[i] = new([]byte)
		case projectmember.FieldRoleCode:
			values[i] = new(sql.NullString)
		case projectmember.FieldJoinedAt, projectmember.FieldLeftAt:
			values[i] = new(sql.NullTime)
		case projectmember.FieldID, projectmember.FieldTenantID, projectmember.FieldProjectID, projectmember.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProjectMember fields.
func (_m *ProjectMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case projectmember.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case projectmember.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case projectmember.FieldProjectID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value != nil {
				_m.ProjectID = *value
			}
		case projectmember.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case projectmember.FieldRoleCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role_code", values[i])
			} else if value.Valid {
				_m.RoleCode = value.String
			}
		case projectmember.FieldJoinedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field joined_at", values[i])
			} else if value.Valid {
				_m.JoinedAt = value.Time
			}
		case projectmember.FieldLeftAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field left_at", values[i])
			} else if value.Valid {
				_m.LeftAt = value.Time
			}
		case projectmember.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProjectMember.
// This includes values selected through modifiers, order, etc.
func (_m *ProjectMember) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the ProjectMember entity.
func (_m *ProjectMember) QueryProject() *ProjectQuery {
	return NewProjectMemberClient(_m.config).QueryProject(_m)
}

// Update returns a builder for updating this ProjectMember.
// Note that you need to call ProjectMember.Unwrap() before calling this method if this ProjectMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProjectMember) Update() *ProjectMemberUpdateOne {
	return NewProjectMemberClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProjectMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProjectMember) Unwrap() *ProjectMember {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProjectMember is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProjectMember) String() string {
	var builder strings.Builder
	builder.WriteString("ProjectMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("role_code=")
	builder.WriteString(_m.RoleCode)
	builder.WriteString(", ")
	builder.WriteString("joined_at=")
	builder.WriteString(_m.JoinedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("left_at=")
	builder.WriteString(_m.LeftAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteByte(')')
	return builder.String()
}

// ProjectMembers is a parsable slice of ProjectMember.
type ProjectMembers []*ProjectMember
