// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/projects-service/internal/ent/predicate"
	"github.com/bengobox/projects-service/internal/ent/project"
	"github.com/bengobox/projects-service/internal/ent/projectmember"
	"github.com/google/uuid"
)

// ProjectMemberUpdate is the builder for updating ProjectMember entities.
type ProjectMemberUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectMemberMutation
}

// Where appends a list predicates to the ProjectMemberUpdate builder.
func (_u *ProjectMemberUpdate) Where(ps ...predicate.ProjectMember) *ProjectMemberUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ProjectMemberUpdate) SetTenantID(v uuid.UUID) *ProjectMemberUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ProjectMemberUpdate) SetNillableTenantID(v *uuid.UUID) *ProjectMemberUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *ProjectMemberUpdate) SetProjectID(v uuid.UUID) *ProjectMemberUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ProjectMemberUpdate) SetNillableProjectID(v *uuid.UUID) *ProjectMemberUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ProjectMemberUpdate) SetUserID(v uuid.UUID) *ProjectMemberUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ProjectMemberUpdate) SetNillableUserID(v *uuid.UUID) *ProjectMemberUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRoleCode sets the "role_code" field.
func (_u *ProjectMemberUpdate) SetRoleCode(v string) *ProjectMemberUpdate {
	_u.mutation.SetRoleCode(v)
	return _u
}

// SetNillableRoleCode sets the "role_code" field if the given value is not nil.
func (_u *ProjectMemberUpdate) SetNillableRoleCode(v *string) *ProjectMemberUpdate {
	if v != nil {
		_u.SetRoleCode(*v)
	}
	return _u
}

// SetJoinedAt sets the "joined_at" field.
func (_u *ProjectMemberUpdate) SetJoinedAt(v time.Time) *ProjectMemberUpdate {
	_u.mutation.SetJoinedAt(v)
	return _u
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_u *ProjectMemberUpdate) SetNillableJoinedAt(v *time.Time) *ProjectMemberUpdate {
	if v != nil {
		_u.SetJoinedAt(*v)
	}
	return _u
}

// SetLeftAt sets the "left_at" field.
func (_u *ProjectMemberUpdate) SetLeftAt(v time.Time) *ProjectMemberUpdate {
	_u.mutation.SetLeftAt(v)
	return _u
}

// SetNillableLeftAt sets the "left_at" field if the given value is not nil.
func (_u *ProjectMemberUpdate) SetNillableLeftAt(v *time.Time) *ProjectMemberUpdate {
	if v != nil {
		_u.SetLeftAt(*v)
	}
	return _u
}

// ClearLeftAt clears the value of the "left_at" field.
func (_u *ProjectMemberUpdate) ClearLeftAt() *ProjectMemberUpdate {
	_u.mutation.ClearLeftAt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ProjectMemberUpdate) SetMetadata(v map[string]interface{}) *ProjectMemberUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *ProjectMemberUpdate) ClearMetadata() *ProjectMemberUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ProjectMemberUpdate) SetProject(v *Project) *ProjectMemberUpdate {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the ProjectMemberMutation object of the builder.
func (_u *ProjectMemberUpdate) Mutation() *ProjectMemberMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ProjectMemberUpdate) ClearProject() *ProjectMemberUpdate {
	_u.mutation.ClearProject()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectMemberUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectMemberUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectMemberUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectMemberUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectMemberUpdate) check() error {
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectMember.project"`)
	}
	return nil
}

func (_u *ProjectMemberUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projectmember.Table, projectmember.Columns, sqlgraph.NewFieldSpec(projectmember.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(projectmember.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(projectmember.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.RoleCode(); ok {
		_spec.SetField(projectmember.FieldRoleCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.JoinedAt(); ok {
		_spec.SetField(projectmember.FieldJoinedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LeftAt(); ok {
		_spec.SetField(projectmember.FieldLeftAt, field.TypeTime, value)
	}
	if _u.mutation.LeftAtCleared() {
		_spec.ClearField(projectmember.FieldLeftAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(projectmember.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(projectmember.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectmember.ProjectTable,
			Columns: []string{projectmember.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectmember.ProjectTable,
			Columns: []string{projectmember.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectMemberUpdateOne is the builder for updating a single ProjectMember entity.
type ProjectMemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectMemberMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *ProjectMemberUpdateOne) SetTenantID(v uuid.UUID) *ProjectMemberUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ProjectMemberUpdateOne) SetNillableTenantID(v *uuid.UUID) *ProjectMemberUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *ProjectMemberUpdateOne) SetProjectID(v uuid.UUID) *ProjectMemberUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *ProjectMemberUpdateOne) SetNillableProjectID(v *uuid.UUID) *ProjectMemberUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ProjectMemberUpdateOne) SetUserID(v uuid.UUID) *ProjectMemberUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ProjectMemberUpdateOne) SetNillableUserID(v *uuid.UUID) *ProjectMemberUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRoleCode sets the "role_code" field.
func (_u *ProjectMemberUpdateOne) SetRoleCode(v string) *ProjectMemberUpdateOne {
	_u.mutation.SetRoleCode(v)
	return _u
}

// SetNillableRoleCode sets the "role_code" field if the given value is not nil.
func (_u *ProjectMemberUpdateOne) SetNillableRoleCode(v *string) *ProjectMemberUpdateOne {
	if v != nil {
		_u.SetRoleCode(*v)
	}
	return _u
}

// SetJoinedAt sets the "joined_at" field.
func (_u *ProjectMemberUpdateOne) SetJoinedAt(v time.Time) *ProjectMemberUpdateOne {
	_u.mutation.SetJoinedAt(v)
	return _u
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_u *ProjectMemberUpdateOne) SetNillableJoinedAt(v *time.Time) *ProjectMemberUpdateOne {
	if v != nil {
		_u.SetJoinedAt(*v)
	}
	return _u
}

// SetLeftAt sets the "left_at" field.
func (_u *ProjectMemberUpdateOne) SetLeftAt(v time.Time) *ProjectMemberUpdateOne {
	_u.mutation.SetLeftAt(v)
	return _u
}

// SetNillableLeftAt sets the "left_at" field if the given value is not nil.
func (_u *ProjectMemberUpdateOne) SetNillableLeftAt(v *time.Time) *ProjectMemberUpdateOne {
	if v != nil {
		_u.SetLeftAt(*v)
	}
	return _u
}

// ClearLeftAt clears the value of the "left_at" field.
func (_u *ProjectMemberUpdateOne) ClearLeftAt() *ProjectMemberUpdateOne {
	_u.mutation.ClearLeftAt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ProjectMemberUpdateOne) SetMetadata(v map[string]interface{}) *ProjectMemberUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *ProjectMemberUpdateOne) ClearMetadata() *ProjectMemberUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *ProjectMemberUpdateOne) SetProject(v *Project) *ProjectMemberUpdateOne {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the ProjectMemberMutation object of the builder.
func (_u *ProjectMemberUpdateOne) Mutation() *ProjectMemberMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *ProjectMemberUpdateOne) ClearProject() *ProjectMemberUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// Where appends a list predicates to the ProjectMemberUpdate builder.
func (_u *ProjectMemberUpdateOne) Where(ps ...predicate.ProjectMember) *ProjectMemberUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectMemberUpdateOne) Select(field string, fields ...string) *ProjectMemberUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProjectMember entity.
func (_u *ProjectMemberUpdateOne) Save(ctx context.Context) (*ProjectMember, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectMemberUpdateOne) SaveX(ctx context.Context) *ProjectMember {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectMemberUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectMemberUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectMemberUpdateOne) check() error {
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProjectMember.project"`)
	}
	return nil
}

func (_u *ProjectMemberUpdateOne) sqlSave(ctx context.Context) (_node *ProjectMember, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(projectmember.Table, projectmember.Columns, sqlgraph.NewFieldSpec(projectmember.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProjectMember.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, projectmember.FieldID)
		for _, f := range fields {
			if !projectmember.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != projectmember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(projectmember.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(projectmember.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.RoleCode(); ok {
		_spec.SetField(projectmember.FieldRoleCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.JoinedAt(); ok {
		_spec.SetField(projectmember.FieldJoinedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LeftAt(); ok {
		_spec.SetField(projectmember.FieldLeftAt, field.TypeTime, value)
	}
	if _u.mutation.LeftAtCleared() {
		_spec.ClearField(projectmember.FieldLeftAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(projectmember.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(projectmember.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectmember.ProjectTable,
			Columns: []string{projectmember.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   projectmember.ProjectTable,
			Columns: []string{projectmember.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProjectMember{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{projectmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
