// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/projects-service/internal/ent/activity"
	"github.com/bengobox/projects-service/internal/ent/attachment"
	"github.com/bengobox/projects-service/internal/ent/comment"
	"github.com/bengobox/projects-service/internal/ent/predicate"
	"github.com/bengobox/projects-service/internal/ent/project"
	"github.com/bengobox/projects-service/internal/ent/task"
	"github.com/bengobox/projects-service/internal/ent/taskdependency"
	"github.com/google/uuid"
)

// TaskUpdate is the builder for updating Task entities.
type TaskUpdate struct {
	config
	hooks    []Hook
	mutation *TaskMutation
}

// Where appends a list predicates to the TaskUpdate builder.
func (tu *TaskUpdate) Where(ps ...predicate.Task) *TaskUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetTenantID sets the "tenant_id" field.
func (tu *TaskUpdate) SetTenantID(u uuid.UUID) *TaskUpdate {
	tu.mutation.SetTenantID(u)
	return tu
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableTenantID(u *uuid.UUID) *TaskUpdate {
	if u != nil {
		tu.SetTenantID(*u)
	}
	return tu
}

// SetProjectID sets the "project_id" field.
func (tu *TaskUpdate) SetProjectID(u uuid.UUID) *TaskUpdate {
	tu.mutation.SetProjectID(u)
	return tu
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableProjectID(u *uuid.UUID) *TaskUpdate {
	if u != nil {
		tu.SetProjectID(*u)
	}
	return tu
}

// SetTitle sets the "title" field.
func (tu *TaskUpdate) SetTitle(s string) *TaskUpdate {
	tu.mutation.SetTitle(s)
	return tu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableTitle(s *string) *TaskUpdate {
	if s != nil {
		tu.SetTitle(*s)
	}
	return tu
}

// SetDescription sets the "description" field.
func (tu *TaskUpdate) SetDescription(s string) *TaskUpdate {
	tu.mutation.SetDescription(s)
	return tu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableDescription(s *string) *TaskUpdate {
	if s != nil {
		tu.SetDescription(*s)
	}
	return tu
}

// ClearDescription clears the value of the "description" field.
func (tu *TaskUpdate) ClearDescription() *TaskUpdate {
	tu.mutation.ClearDescription()
	return tu
}

// SetStatus sets the "status" field.
func (tu *TaskUpdate) SetStatus(s string) *TaskUpdate {
	tu.mutation.SetStatus(s)
	return tu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableStatus(s *string) *TaskUpdate {
	if s != nil {
		tu.SetStatus(*s)
	}
	return tu
}

// SetPriority sets the "priority" field.
func (tu *TaskUpdate) SetPriority(s string) *TaskUpdate {
	tu.mutation.SetPriority(s)
	return tu
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (tu *TaskUpdate) SetNillablePriority(s *string) *TaskUpdate {
	if s != nil {
		tu.SetPriority(*s)
	}
	return tu
}

// SetAssigneeID sets the "assignee_id" field.
func (tu *TaskUpdate) SetAssigneeID(u uuid.UUID) *TaskUpdate {
	tu.mutation.SetAssigneeID(u)
	return tu
}

// SetNillableAssigneeID sets the "assignee_id" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableAssigneeID(u *uuid.UUID) *TaskUpdate {
	if u != nil {
		tu.SetAssigneeID(*u)
	}
	return tu
}

// ClearAssigneeID clears the value of the "assignee_id" field.
func (tu *TaskUpdate) ClearAssigneeID() *TaskUpdate {
	tu.mutation.ClearAssigneeID()
	return tu
}

// SetDueDate sets the "due_date" field.
func (tu *TaskUpdate) SetDueDate(t time.Time) *TaskUpdate {
	tu.mutation.SetDueDate(t)
	return tu
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableDueDate(t *time.Time) *TaskUpdate {
	if t != nil {
		tu.SetDueDate(*t)
	}
	return tu
}

// ClearDueDate clears the value of the "due_date" field.
func (tu *TaskUpdate) ClearDueDate() *TaskUpdate {
	tu.mutation.ClearDueDate()
	return tu
}

// SetCompletedAt sets the "completed_at" field.
func (tu *TaskUpdate) SetCompletedAt(t time.Time) *TaskUpdate {
	tu.mutation.SetCompletedAt(t)
	return tu
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableCompletedAt(t *time.Time) *TaskUpdate {
	if t != nil {
		tu.SetCompletedAt(*t)
	}
	return tu
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (tu *TaskUpdate) ClearCompletedAt() *TaskUpdate {
	tu.mutation.ClearCompletedAt()
	return tu
}

// SetUpdatedAt sets the "updated_at" field.
func (tu *TaskUpdate) SetUpdatedAt(t time.Time) *TaskUpdate {
	tu.mutation.SetUpdatedAt(t)
	return tu
}

// SetMetadata sets the "metadata" field.
func (tu *TaskUpdate) SetMetadata(m map[string]interface{}) *TaskUpdate {
	tu.mutation.SetMetadata(m)
	return tu
}

// ClearMetadata clears the value of the "metadata" field.
func (tu *TaskUpdate) ClearMetadata() *TaskUpdate {
	tu.mutation.ClearMetadata()
	return tu
}

// SetParentID sets the "parent_id" field.
func (tu *TaskUpdate) SetParentID(u uuid.UUID) *TaskUpdate {
	tu.mutation.SetParentID(u)
	return tu
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableParentID(u *uuid.UUID) *TaskUpdate {
	if u != nil {
		tu.SetParentID(*u)
	}
	return tu
}

// ClearParentID clears the value of the "parent_id" field.
func (tu *TaskUpdate) ClearParentID() *TaskUpdate {
	tu.mutation.ClearParentID()
	return tu
}

// SetWbsCode sets the "wbs_code" field.
func (tu *TaskUpdate) SetWbsCode(s string) *TaskUpdate {
	tu.mutation.SetWbsCode(s)
	return tu
}

// SetNillableWbsCode sets the "wbs_code" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableWbsCode(s *string) *TaskUpdate {
	if s != nil {
		tu.SetWbsCode(*s)
	}
	return tu
}

// ClearWbsCode clears the value of the "wbs_code" field.
func (tu *TaskUpdate) ClearWbsCode() *TaskUpdate {
	tu.mutation.ClearWbsCode()
	return tu
}

// SetProject sets the "project" edge to the Project entity.
func (tu *TaskUpdate) SetProject(p *Project) *TaskUpdate {
	return tu.SetProjectID(p.ID)
}

// AddDependencyIDs adds the "dependencies" edge to the TaskDependency entity by IDs.
func (tu *TaskUpdate) AddDependencyIDs(ids ...uuid.UUID) *TaskUpdate {
	tu.mutation.AddDependencyIDs(ids...)
	return tu
}

// AddDependencies adds the "dependencies" edges to the TaskDependency entity.
func (tu *TaskUpdate) AddDependencies(t ...*TaskDependency) *TaskUpdate {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tu.AddDependencyIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (tu *TaskUpdate) AddCommentIDs(ids ...uuid.UUID) *TaskUpdate {
	tu.mutation.AddCommentIDs(ids...)
	return tu
}

// AddComments adds the "comments" edges to the Comment entity.
func (tu *TaskUpdate) AddComments(c ...*Comment) *TaskUpdate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return tu.AddCommentIDs(ids...)
}

// AddActivityIDs adds the "activities" edge to the Activity entity by IDs.
func (tu *TaskUpdate) AddActivityIDs(ids ...uuid.UUID) *TaskUpdate {
	tu.mutation.AddActivityIDs(ids...)
	return tu
}

// AddActivities adds the "activities" edges to the Activity entity.
func (tu *TaskUpdate) AddActivities(a ...*Activity) *TaskUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return tu.AddActivityIDs(ids...)
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (tu *TaskUpdate) AddAttachmentIDs(ids ...uuid.UUID) *TaskUpdate {
	tu.mutation.AddAttachmentIDs(ids...)
	return tu
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (tu *TaskUpdate) AddAttachments(a ...*Attachment) *TaskUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return tu.AddAttachmentIDs(ids...)
}

// Mutation returns the TaskMutation object of the builder.
func (tu *TaskUpdate) Mutation() *TaskMutation {
	return tu.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (tu *TaskUpdate) ClearProject() *TaskUpdate {
	tu.mutation.ClearProject()
	return tu
}

// ClearDependencies clears all "dependencies" edges to the TaskDependency entity.
func (tu *TaskUpdate) ClearDependencies() *TaskUpdate {
	tu.mutation.ClearDependencies()
	return tu
}

// RemoveDependencyIDs removes the "dependencies" edge to TaskDependency entities by IDs.
func (tu *TaskUpdate) RemoveDependencyIDs(ids ...uuid.UUID) *TaskUpdate {
	tu.mutation.RemoveDependencyIDs(ids...)
	return tu
}

// RemoveDependencies removes "dependencies" edges to TaskDependency entities.
func (tu *TaskUpdate) RemoveDependencies(t ...*TaskDependency) *TaskUpdate {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tu.RemoveDependencyIDs(ids...)
}

// ClearComments clears all "comments" edges to the Comment entity.
func (tu *TaskUpdate) ClearComments() *TaskUpdate {
	tu.mutation.ClearComments()
	return tu
}

// RemoveCommentIDs removes the "comments" edge to Comment entities by IDs.
func (tu *TaskUpdate) RemoveCommentIDs(ids ...uuid.UUID) *TaskUpdate {
	tu.mutation.RemoveCommentIDs(ids...)
	return tu
}

// RemoveComments removes "comments" edges to Comment entities.
func (tu *TaskUpdate) RemoveComments(c ...*Comment) *TaskUpdate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return tu.RemoveCommentIDs(ids...)
}

// ClearActivities clears all "activities" edges to the Activity entity.
func (tu *TaskUpdate) ClearActivities() *TaskUpdate {
	tu.mutation.ClearActivities()
	return tu
}

// RemoveActivityIDs removes the "activities" edge to Activity entities by IDs.
func (tu *TaskUpdate) RemoveActivityIDs(ids ...uuid.UUID) *TaskUpdate {
	tu.mutation.RemoveActivityIDs(ids...)
	return tu
}

// RemoveActivities removes "activities" edges to Activity entities.
func (tu *TaskUpdate) RemoveActivities(a ...*Activity) *TaskUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return tu.RemoveActivityIDs(ids...)
}

// ClearAttachments clears all "attachments" edges to the Attachment entity.
func (tu *TaskUpdate) ClearAttachments() *TaskUpdate {
	tu.mutation.ClearAttachments()
	return tu
}

// RemoveAttachmentIDs removes the "attachments" edge to Attachment entities by IDs.
func (tu *TaskUpdate) RemoveAttachmentIDs(ids ...uuid.UUID) *TaskUpdate {
	tu.mutation.RemoveAttachmentIDs(ids...)
	return tu
}

// RemoveAttachments removes "attachments" edges to Attachment entities.
func (tu *TaskUpdate) RemoveAttachments(a ...*Attachment) *TaskUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return tu.RemoveAttachmentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TaskUpdate) Save(ctx context.Context) (int, error) {
	tu.defaults()
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TaskUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TaskUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TaskUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tu *TaskUpdate) defaults() {
	if _, ok := tu.mutation.UpdatedAt(); !ok {
		v := task.UpdateDefaultUpdatedAt()
		tu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tu *TaskUpdate) check() error {
	if v, ok := tu.mutation.Title(); ok {
		if err := task.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Task.title": %w`, err)}
		}
	}
	if _, ok := tu.mutation.ProjectID(); tu.mutation.ProjectCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Task.project"`)
	}
	return nil
}

func (tu *TaskUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.TenantID(); ok {
		_spec.SetField(task.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := tu.mutation.Title(); ok {
		_spec.SetField(task.FieldTitle, field.TypeString, value)
	}
	if value, ok := tu.mutation.Description(); ok {
		_spec.SetField(task.FieldDescription, field.TypeString, value)
	}
	if tu.mutation.DescriptionCleared() {
		_spec.ClearField(task.FieldDescription, field.TypeString)
	}
	if value, ok := tu.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeString, value)
	}
	if value, ok := tu.mutation.Priority(); ok {
		_spec.SetField(task.FieldPriority, field.TypeString, value)
	}
	if value, ok := tu.mutation.AssigneeID(); ok {
		_spec.SetField(task.FieldAssigneeID, field.TypeUUID, value)
	}
	if tu.mutation.AssigneeIDCleared() {
		_spec.ClearField(task.FieldAssigneeID, field.TypeUUID)
	}
	if value, ok := tu.mutation.DueDate(); ok {
		_spec.SetField(task.FieldDueDate, field.TypeTime, value)
	}
	if tu.mutation.DueDateCleared() {
		_spec.ClearField(task.FieldDueDate, field.TypeTime)
	}
	if value, ok := tu.mutation.CompletedAt(); ok {
		_spec.SetField(task.FieldCompletedAt, field.TypeTime, value)
	}
	if tu.mutation.CompletedAtCleared() {
		_spec.ClearField(task.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := tu.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tu.mutation.Metadata(); ok {
		_spec.SetField(task.FieldMetadata, field.TypeJSON, value)
	}
	if tu.mutation.MetadataCleared() {
		_spec.ClearField(task.FieldMetadata, field.TypeJSON)
	}
	if value, ok := tu.mutation.ParentID(); ok {
		_spec.SetField(task.FieldParentID, field.TypeUUID, value)
	}
	if tu.mutation.ParentIDCleared() {
		_spec.ClearField(task.FieldParentID, field.TypeUUID)
	}
	if value, ok := tu.mutation.WbsCode(); ok {
		_spec.SetField(task.FieldWbsCode, field.TypeString, value)
	}
	if tu.mutation.WbsCodeCleared() {
		_spec.ClearField(task.FieldWbsCode, field.TypeString)
	}
	if tu.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ProjectTable,
			Columns: []string{task.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ProjectTable,
			Columns: []string{task.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.DependenciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.DependenciesTable,
			Columns: []string{task.DependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskdependency.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedDependenciesIDs(); len(nodes) > 0 && !tu.mutation.DependenciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.DependenciesTable,
			Columns: []string{task.DependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskdependency.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.DependenciesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.DependenciesTable,
			Columns: []string{task.DependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskdependency.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CommentsTable,
			Columns: []string{task.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !tu.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CommentsTable,
			Columns: []string{task.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CommentsTable,
			Columns: []string{task.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.ActivitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ActivitiesTable,
			Columns: []string{task.ActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedActivitiesIDs(); len(nodes) > 0 && !tu.mutation.ActivitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ActivitiesTable,
			Columns: []string{task.ActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.ActivitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ActivitiesTable,
			Columns: []string{task.ActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.AttachmentsTable,
			Columns: []string{task.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !tu.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.AttachmentsTable,
			Columns: []string{task.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.AttachmentsTable,
			Columns: []string{task.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TaskUpdateOne is the builder for updating a single Task entity.
type TaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskMutation
}

// SetTenantID sets the "tenant_id" field.
func (tuo *TaskUpdateOne) SetTenantID(u uuid.UUID) *TaskUpdateOne {
	tuo.mutation.SetTenantID(u)
	return tuo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableTenantID(u *uuid.UUID) *TaskUpdateOne {
	if u != nil {
		tuo.SetTenantID(*u)
	}
	return tuo
}

// SetProjectID sets the "project_id" field.
func (tuo *TaskUpdateOne) SetProjectID(u uuid.UUID) *TaskUpdateOne {
	tuo.mutation.SetProjectID(u)
	return tuo
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableProjectID(u *uuid.UUID) *TaskUpdateOne {
	if u != nil {
		tuo.SetProjectID(*u)
	}
	return tuo
}

// SetTitle sets the "title" field.
func (tuo *TaskUpdateOne) SetTitle(s string) *TaskUpdateOne {
	tuo.mutation.SetTitle(s)
	return tuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableTitle(s *string) *TaskUpdateOne {
	if s != nil {
		tuo.SetTitle(*s)
	}
	return tuo
}

// SetDescription sets the "description" field.
func (tuo *TaskUpdateOne) SetDescription(s string) *TaskUpdateOne {
	tuo.mutation.SetDescription(s)
	return tuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableDescription(s *string) *TaskUpdateOne {
	if s != nil {
		tuo.SetDescription(*s)
	}
	return tuo
}

// ClearDescription clears the value of the "description" field.
func (tuo *TaskUpdateOne) ClearDescription() *TaskUpdateOne {
	tuo.mutation.ClearDescription()
	return tuo
}

// SetStatus sets the "status" field.
func (tuo *TaskUpdateOne) SetStatus(s string) *TaskUpdateOne {
	tuo.mutation.SetStatus(s)
	return tuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableStatus(s *string) *TaskUpdateOne {
	if s != nil {
		tuo.SetStatus(*s)
	}
	return tuo
}

// SetPriority sets the "priority" field.
func (tuo *TaskUpdateOne) SetPriority(s string) *TaskUpdateOne {
	tuo.mutation.SetPriority(s)
	return tuo
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillablePriority(s *string) *TaskUpdateOne {
	if s != nil {
		tuo.SetPriority(*s)
	}
	return tuo
}

// SetAssigneeID sets the "assignee_id" field.
func (tuo *TaskUpdateOne) SetAssigneeID(u uuid.UUID) *TaskUpdateOne {
	tuo.mutation.SetAssigneeID(u)
	return tuo
}

// SetNillableAssigneeID sets the "assignee_id" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableAssigneeID(u *uuid.UUID) *TaskUpdateOne {
	if u != nil {
		tuo.SetAssigneeID(*u)
	}
	return tuo
}

// ClearAssigneeID clears the value of the "assignee_id" field.
func (tuo *TaskUpdateOne) ClearAssigneeID() *TaskUpdateOne {
	tuo.mutation.ClearAssigneeID()
	return tuo
}

// SetDueDate sets the "due_date" field.
func (tuo *TaskUpdateOne) SetDueDate(t time.Time) *TaskUpdateOne {
	tuo.mutation.SetDueDate(t)
	return tuo
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableDueDate(t *time.Time) *TaskUpdateOne {
	if t != nil {
		tuo.SetDueDate(*t)
	}
	return tuo
}

// ClearDueDate clears the value of the "due_date" field.
func (tuo *TaskUpdateOne) ClearDueDate() *TaskUpdateOne {
	tuo.mutation.ClearDueDate()
	return tuo
}

// SetCompletedAt sets the "completed_at" field.
func (tuo *TaskUpdateOne) SetCompletedAt(t time.Time) *TaskUpdateOne {
	tuo.mutation.SetCompletedAt(t)
	return tuo
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableCompletedAt(t *time.Time) *TaskUpdateOne {
	if t != nil {
		tuo.SetCompletedAt(*t)
	}
	return tuo
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (tuo *TaskUpdateOne) ClearCompletedAt() *TaskUpdateOne {
	tuo.mutation.ClearCompletedAt()
	return tuo
}

// SetUpdatedAt sets the "updated_at" field.
func (tuo *TaskUpdateOne) SetUpdatedAt(t time.Time) *TaskUpdateOne {
	tuo.mutation.SetUpdatedAt(t)
	return tuo
}

// SetMetadata sets the "metadata" field.
func (tuo *TaskUpdateOne) SetMetadata(m map[string]interface{}) *TaskUpdateOne {
	tuo.mutation.SetMetadata(m)
	return tuo
}

// ClearMetadata clears the value of the "metadata" field.
func (tuo *TaskUpdateOne) ClearMetadata() *TaskUpdateOne {
	tuo.mutation.ClearMetadata()
	return tuo
}

// SetParentID sets the "parent_id" field.
func (tuo *TaskUpdateOne) SetParentID(u uuid.UUID) *TaskUpdateOne {
	tuo.mutation.SetParentID(u)
	return tuo
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableParentID(u *uuid.UUID) *TaskUpdateOne {
	if u != nil {
		tuo.SetParentID(*u)
	}
	return tuo
}

// ClearParentID clears the value of the "parent_id" field.
func (tuo *TaskUpdateOne) ClearParentID() *TaskUpdateOne {
	tuo.mutation.ClearParentID()
	return tuo
}

// SetWbsCode sets the "wbs_code" field.
func (tuo *TaskUpdateOne) SetWbsCode(s string) *TaskUpdateOne {
	tuo.mutation.SetWbsCode(s)
	return tuo
}

// SetNillableWbsCode sets the "wbs_code" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableWbsCode(s *string) *TaskUpdateOne {
	if s != nil {
		tuo.SetWbsCode(*s)
	}
	return tuo
}

// ClearWbsCode clears the value of the "wbs_code" field.
func (tuo *TaskUpdateOne) ClearWbsCode() *TaskUpdateOne {
	tuo.mutation.ClearWbsCode()
	return tuo
}

// SetProject sets the "project" edge to the Project entity.
func (tuo *TaskUpdateOne) SetProject(p *Project) *TaskUpdateOne {
	return tuo.SetProjectID(p.ID)
}

// AddDependencyIDs adds the "dependencies" edge to the TaskDependency entity by IDs.
func (tuo *TaskUpdateOne) AddDependencyIDs(ids ...uuid.UUID) *TaskUpdateOne {
	tuo.mutation.AddDependencyIDs(ids...)
	return tuo
}

// AddDependencies adds the "dependencies" edges to the TaskDependency entity.
func (tuo *TaskUpdateOne) AddDependencies(t ...*TaskDependency) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tuo.AddDependencyIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the Comment entity by IDs.
func (tuo *TaskUpdateOne) AddCommentIDs(ids ...uuid.UUID) *TaskUpdateOne {
	tuo.mutation.AddCommentIDs(ids...)
	return tuo
}

// AddComments adds the "comments" edges to the Comment entity.
func (tuo *TaskUpdateOne) AddComments(c ...*Comment) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return tuo.AddCommentIDs(ids...)
}

// AddActivityIDs adds the "activities" edge to the Activity entity by IDs.
func (tuo *TaskUpdateOne) AddActivityIDs(ids ...uuid.UUID) *TaskUpdateOne {
	tuo.mutation.AddActivityIDs(ids...)
	return tuo
}

// AddActivities adds the "activities" edges to the Activity entity.
func (tuo *TaskUpdateOne) AddActivities(a ...*Activity) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return tuo.AddActivityIDs(ids...)
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (tuo *TaskUpdateOne) AddAttachmentIDs(ids ...uuid.UUID) *TaskUpdateOne {
	tuo.mutation.AddAttachmentIDs(ids...)
	return tuo
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (tuo *TaskUpdateOne) AddAttachments(a ...*Attachment) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return tuo.AddAttachmentIDs(ids...)
}

// Mutation returns the TaskMutation object of the builder.
func (tuo *TaskUpdateOne) Mutation() *TaskMutation {
	return tuo.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (tuo *TaskUpdateOne) ClearProject() *TaskUpdateOne {
	tuo.mutation.ClearProject()
	return tuo
}

// ClearDependencies clears all "dependencies" edges to the TaskDependency entity.
func (tuo *TaskUpdateOne) ClearDependencies() *TaskUpdateOne {
	tuo.mutation.ClearDependencies()
	return tuo
}

// RemoveDependencyIDs removes the "dependencies" edge to TaskDependency entities by IDs.
func (tuo *TaskUpdateOne) RemoveDependencyIDs(ids ...uuid.UUID) *TaskUpdateOne {
	tuo.mutation.RemoveDependencyIDs(ids...)
	return tuo
}

// RemoveDependencies removes "dependencies" edges to TaskDependency entities.
func (tuo *TaskUpdateOne) RemoveDependencies(t ...*TaskDependency) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tuo.RemoveDependencyIDs(ids...)
}

// ClearComments clears all "comments" edges to the Comment entity.
func (tuo *TaskUpdateOne) ClearComments() *TaskUpdateOne {
	tuo.mutation.ClearComments()
	return tuo
}

// RemoveCommentIDs removes the "comments" edge to Comment entities by IDs.
func (tuo *TaskUpdateOne) RemoveCommentIDs(ids ...uuid.UUID) *TaskUpdateOne {
	tuo.mutation.RemoveCommentIDs(ids...)
	return tuo
}

// RemoveComments removes "comments" edges to Comment entities.
func (tuo *TaskUpdateOne) RemoveComments(c ...*Comment) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return tuo.RemoveCommentIDs(ids...)
}

// ClearActivities clears all "activities" edges to the Activity entity.
func (tuo *TaskUpdateOne) ClearActivities() *TaskUpdateOne {
	tuo.mutation.ClearActivities()
	return tuo
}

// RemoveActivityIDs removes the "activities" edge to Activity entities by IDs.
func (tuo *TaskUpdateOne) RemoveActivityIDs(ids ...uuid.UUID) *TaskUpdateOne {
	tuo.mutation.RemoveActivityIDs(ids...)
	return tuo
}

// RemoveActivities removes "activities" edges to Activity entities.
func (tuo *TaskUpdateOne) RemoveActivities(a ...*Activity) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return tuo.RemoveActivityIDs(ids...)
}

// ClearAttachments clears all "attachments" edges to the Attachment entity.
func (tuo *TaskUpdateOne) ClearAttachments() *TaskUpdateOne {
	tuo.mutation.ClearAttachments()
	return tuo
}

// RemoveAttachmentIDs removes the "attachments" edge to Attachment entities by IDs.
func (tuo *TaskUpdateOne) RemoveAttachmentIDs(ids ...uuid.UUID) *TaskUpdateOne {
	tuo.mutation.RemoveAttachmentIDs(ids...)
	return tuo
}

// RemoveAttachments removes "attachments" edges to Attachment entities.
func (tuo *TaskUpdateOne) RemoveAttachments(a ...*Attachment) *TaskUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return tuo.RemoveAttachmentIDs(ids...)
}

// Where appends a list predicates to the TaskUpdate builder.
func (tuo *TaskUpdateOne) Where(ps ...predicate.Task) *TaskUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TaskUpdateOne) Select(field string, fields ...string) *TaskUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Task entity.
func (tuo *TaskUpdateOne) Save(ctx context.Context) (*Task, error) {
	tuo.defaults()
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TaskUpdateOne) SaveX(ctx context.Context) *Task {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TaskUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TaskUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tuo *TaskUpdateOne) defaults() {
	if _, ok := tuo.mutation.UpdatedAt(); !ok {
		v := task.UpdateDefaultUpdatedAt()
		tuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuo *TaskUpdateOne) check() error {
	if v, ok := tuo.mutation.Title(); ok {
		if err := task.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Task.title": %w`, err)}
		}
	}
	if _, ok := tuo.mutation.ProjectID(); tuo.mutation.ProjectCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Task.project"`)
	}
	return nil
}

func (tuo *TaskUpdateOne) sqlSave(ctx context.Context) (_node *Task, err error) {
	if err := tuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(task.Table, task.Columns, sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Task.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, task.FieldID)
		for _, f := range fields {
			if !task.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != task.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.TenantID(); ok {
		_spec.SetField(task.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := tuo.mutation.Title(); ok {
		_spec.SetField(task.FieldTitle, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Description(); ok {
		_spec.SetField(task.FieldDescription, field.TypeString, value)
	}
	if tuo.mutation.DescriptionCleared() {
		_spec.ClearField(task.FieldDescription, field.TypeString)
	}
	if value, ok := tuo.mutation.Status(); ok {
		_spec.SetField(task.FieldStatus, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Priority(); ok {
		_spec.SetField(task.FieldPriority, field.TypeString, value)
	}
	if value, ok := tuo.mutation.AssigneeID(); ok {
		_spec.SetField(task.FieldAssigneeID, field.TypeUUID, value)
	}
	if tuo.mutation.AssigneeIDCleared() {
		_spec.ClearField(task.FieldAssigneeID, field.TypeUUID)
	}
	if value, ok := tuo.mutation.DueDate(); ok {
		_spec.SetField(task.FieldDueDate, field.TypeTime, value)
	}
	if tuo.mutation.DueDateCleared() {
		_spec.ClearField(task.FieldDueDate, field.TypeTime)
	}
	if value, ok := tuo.mutation.CompletedAt(); ok {
		_spec.SetField(task.FieldCompletedAt, field.TypeTime, value)
	}
	if tuo.mutation.CompletedAtCleared() {
		_spec.ClearField(task.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := tuo.mutation.UpdatedAt(); ok {
		_spec.SetField(task.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.Metadata(); ok {
		_spec.SetField(task.FieldMetadata, field.TypeJSON, value)
	}
	if tuo.mutation.MetadataCleared() {
		_spec.ClearField(task.FieldMetadata, field.TypeJSON)
	}
	if value, ok := tuo.mutation.ParentID(); ok {
		_spec.SetField(task.FieldParentID, field.TypeUUID, value)
	}
	if tuo.mutation.ParentIDCleared() {
		_spec.ClearField(task.FieldParentID, field.TypeUUID)
	}
	if value, ok := tuo.mutation.WbsCode(); ok {
		_spec.SetField(task.FieldWbsCode, field.TypeString, value)
	}
	if tuo.mutation.WbsCodeCleared() {
		_spec.ClearField(task.FieldWbsCode, field.TypeString)
	}
	if tuo.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ProjectTable,
			Columns: []string{task.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ProjectTable,
			Columns: []string{task.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.DependenciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.DependenciesTable,
			Columns: []string{task.DependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskdependency.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedDependenciesIDs(); len(nodes) > 0 && !tuo.mutation.DependenciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.DependenciesTable,
			Columns: []string{task.DependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskdependency.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.DependenciesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.DependenciesTable,
			Columns: []string{task.DependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(taskdependency.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CommentsTable,
			Columns: []string{task.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedCommentsIDs(); len(nodes) > 0 && !tuo.mutation.CommentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CommentsTable,
			Columns: []string{task.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.CommentsTable,
			Columns: []string{task.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.ActivitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ActivitiesTable,
			Columns: []string{task.ActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedActivitiesIDs(); len(nodes) > 0 && !tuo.mutation.ActivitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ActivitiesTable,
			Columns: []string{task.ActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.ActivitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.ActivitiesTable,
			Columns: []string{task.ActivitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.AttachmentsTable,
			Columns: []string{task.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedAttachmentsIDs(); len(nodes) > 0 && !tuo.mutation.AttachmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.AttachmentsTable,
			Columns: []string{task.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   task.AttachmentsTable,
			Columns: []string{task.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Task{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
