// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/projects-service/internal/ent/task"
	"github.com/bengobox/projects-service/internal/ent/taskdependency"
	"github.com/google/uuid"
)

// TaskDependencyCreate is the builder for creating a TaskDependency entity.
type TaskDependencyCreate struct {
	config
	mutation *TaskDependencyMutation
	hooks    []Hook
}

// SetTaskID sets the "task_id" field.
func (tdc *TaskDependencyCreate) SetTaskID(u uuid.UUID) *TaskDependencyCreate {
	tdc.mutation.SetTaskID(u)
	return tdc
}

// SetDependsOnTaskID sets the "depends_on_task_id" field.
func (tdc *TaskDependencyCreate) SetDependsOnTaskID(u uuid.UUID) *TaskDependencyCreate {
	tdc.mutation.SetDependsOnTaskID(u)
	return tdc
}

// SetDependencyType sets the "dependency_type" field.
func (tdc *TaskDependencyCreate) SetDependencyType(s string) *TaskDependencyCreate {
	tdc.mutation.SetDependencyType(s)
	return tdc
}

// SetNillableDependencyType sets the "dependency_type" field if the given value is not nil.
func (tdc *TaskDependencyCreate) SetNillableDependencyType(s *string) *TaskDependencyCreate {
	if s != nil {
		tdc.SetDependencyType(*s)
	}
	return tdc
}

// SetCreatedAt sets the "created_at" field.
func (tdc *TaskDependencyCreate) SetCreatedAt(t time.Time) *TaskDependencyCreate {
	tdc.mutation.SetCreatedAt(t)
	return tdc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tdc *TaskDependencyCreate) SetNillableCreatedAt(t *time.Time) *TaskDependencyCreate {
	if t != nil {
		tdc.SetCreatedAt(*t)
	}
	return tdc
}

// SetID sets the "id" field.
func (tdc *TaskDependencyCreate) SetID(u uuid.UUID) *TaskDependencyCreate {
	tdc.mutation.SetID(u)
	return tdc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (tdc *TaskDependencyCreate) SetNillableID(u *uuid.UUID) *TaskDependencyCreate {
	if u != nil {
		tdc.SetID(*u)
	}
	return tdc
}

// SetTask sets the "task" edge to the Task entity.
func (tdc *TaskDependencyCreate) SetTask(t *Task) *TaskDependencyCreate {
	return tdc.SetTaskID(t.ID)
}

// Mutation returns the TaskDependencyMutation object of the builder.
func (tdc *TaskDependencyCreate) Mutation() *TaskDependencyMutation {
	return tdc.mutation
}

// Save creates the TaskDependency in the database.
func (tdc *TaskDependencyCreate) Save(ctx context.Context) (*TaskDependency, error) {
	tdc.defaults()
	return withHooks(ctx, tdc.sqlSave, tdc.mutation, tdc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tdc *TaskDependencyCreate) SaveX(ctx context.Context) *TaskDependency {
	v, err := tdc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tdc *TaskDependencyCreate) Exec(ctx context.Context) error {
	_, err := tdc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tdc *TaskDependencyCreate) ExecX(ctx context.Context) {
	if err := tdc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tdc *TaskDependencyCreate) defaults() {
	if _, ok := tdc.mutation.DependencyType(); !ok {
		v := taskdependency.DefaultDependencyType
		tdc.mutation.SetDependencyType(v)
	}
	if _, ok := tdc.mutation.CreatedAt(); !ok {
		v := taskdependency.DefaultCreatedAt()
		tdc.mutation.SetCreatedAt(v)
	}
	if _, ok := tdc.mutation.ID(); !ok {
		v := taskdependency.DefaultID()
		tdc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tdc *TaskDependencyCreate) check() error {
	if _, ok := tdc.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "TaskDependency.task_id"`)}
	}
	if _, ok := tdc.mutation.DependsOnTaskID(); !ok {
		return &ValidationError{Name: "depends_on_task_id", err: errors.New(`ent: missing required field "TaskDependency.depends_on_task_id"`)}
	}
	if _, ok := tdc.mutation.DependencyType(); !ok {
		return &ValidationError{Name: "dependency_type", err: errors.New(`ent: missing required field "TaskDependency.dependency_type"`)}
	}
	if _, ok := tdc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TaskDependency.created_at"`)}
	}
	if _, ok := tdc.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "TaskDependency.task"`)}
	}
	return nil
}

func (tdc *TaskDependencyCreate) sqlSave(ctx context.Context) (*TaskDependency, error) {
	if err := tdc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tdc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tdc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	tdc.mutation.id = &_node.ID
	tdc.mutation.done = true
	return _node, nil
}

func (tdc *TaskDependencyCreate) createSpec() (*TaskDependency, *sqlgraph.CreateSpec) {
	var (
		_node = &TaskDependency{config: tdc.config}
		_spec = sqlgraph.NewCreateSpec(taskdependency.Table, sqlgraph.NewFieldSpec(taskdependency.FieldID, field.TypeUUID))
	)
	if id, ok := tdc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := tdc.mutation.DependsOnTaskID(); ok {
		_spec.SetField(taskdependency.FieldDependsOnTaskID, field.TypeUUID, value)
		_node.DependsOnTaskID = value
	}
	if value, ok := tdc.mutation.DependencyType(); ok {
		_spec.SetField(taskdependency.FieldDependencyType, field.TypeString, value)
		_node.DependencyType = value
	}
	if value, ok := tdc.mutation.CreatedAt(); ok {
		_spec.SetField(taskdependency.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := tdc.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskdependency.TaskTable,
			Columns: []string{taskdependency.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TaskDependencyCreateBulk is the builder for creating many TaskDependency entities in bulk.
type TaskDependencyCreateBulk struct {
	config
	err      error
	builders []*TaskDependencyCreate
}

// Save creates the TaskDependency entities in the database.
func (tdcb *TaskDependencyCreateBulk) Save(ctx context.Context) ([]*TaskDependency, error) {
	if tdcb.err != nil {
		return nil, tdcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tdcb.builders))
	nodes := make([]*TaskDependency, len(tdcb.builders))
	mutators := make([]Mutator, len(tdcb.builders))
	for i := range tdcb.builders {
		func(i int, root context.Context) {
			builder := tdcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskDependencyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tdcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tdcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tdcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tdcb *TaskDependencyCreateBulk) SaveX(ctx context.Context) []*TaskDependency {
	v, err := tdcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tdcb *TaskDependencyCreateBulk) Exec(ctx context.Context) error {
	_, err := tdcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tdcb *TaskDependencyCreateBulk) ExecX(ctx context.Context) {
	if err := tdcb.Exec(ctx); err != nil {
		panic(err)
	}
}
