// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/projects-service/internal/ent/predicate"
	"github.com/bengobox/projects-service/internal/ent/tenantsyncevent"
)

// TenantSyncEventDelete is the builder for deleting a TenantSyncEvent entity.
type TenantSyncEventDelete struct {
	config
	hooks    []Hook
	mutation *TenantSyncEventMutation
}

// Where appends a list predicates to the TenantSyncEventDelete builder.
func (_d *TenantSyncEventDelete) Where(ps ...predicate.TenantSyncEvent) *TenantSyncEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TenantSyncEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TenantSyncEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TenantSyncEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tenantsyncevent.Table, sqlgraph.NewFieldSpec(tenantsyncevent.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TenantSyncEventDeleteOne is the builder for deleting a single TenantSyncEvent entity.
type TenantSyncEventDeleteOne struct {
	_d *TenantSyncEventDelete
}

// Where appends a list predicates to the TenantSyncEventDelete builder.
func (_d *TenantSyncEventDeleteOne) Where(ps ...predicate.TenantSyncEvent) *TenantSyncEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TenantSyncEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tenantsyncevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TenantSyncEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
