// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/projects-service/internal/ent/predicate"
	"github.com/bengobox/projects-service/internal/ent/tendercommittee"
)

// TenderCommitteeDelete is the builder for deleting a TenderCommittee entity.
type TenderCommitteeDelete struct {
	config
	hooks    []Hook
	mutation *TenderCommitteeMutation
}

// Where appends a list predicates to the TenderCommitteeDelete builder.
func (tcd *TenderCommitteeDelete) Where(ps ...predicate.TenderCommittee) *TenderCommitteeDelete {
	tcd.mutation.Where(ps...)
	return tcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tcd *TenderCommitteeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tcd.sqlExec, tcd.mutation, tcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tcd *TenderCommitteeDelete) ExecX(ctx context.Context) int {
	n, err := tcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tcd *TenderCommitteeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tendercommittee.Table, sqlgraph.NewFieldSpec(tendercommittee.FieldID, field.TypeUUID))
	if ps := tcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tcd.mutation.done = true
	return affected, err
}

// TenderCommitteeDeleteOne is the builder for deleting a single TenderCommittee entity.
type TenderCommitteeDeleteOne struct {
	tcd *TenderCommitteeDelete
}

// Where appends a list predicates to the TenderCommitteeDelete builder.
func (tcdo *TenderCommitteeDeleteOne) Where(ps ...predicate.TenderCommittee) *TenderCommitteeDeleteOne {
	tcdo.tcd.mutation.Where(ps...)
	return tcdo
}

// Exec executes the deletion query.
func (tcdo *TenderCommitteeDeleteOne) Exec(ctx context.Context) error {
	n, err := tcdo.tcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tendercommittee.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tcdo *TenderCommitteeDeleteOne) ExecX(ctx context.Context) {
	if err := tcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
