// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/projects-service/internal/ent/tender"
	"github.com/bengobox/projects-service/internal/ent/tenderevaluation"
	"github.com/google/uuid"
)

// TenderEvaluationCreate is the builder for creating a TenderEvaluation entity.
type TenderEvaluationCreate struct {
	config
	mutation *TenderEvaluationMutation
	hooks    []Hook
}

// SetTenderID sets the "tender_id" field.
func (tec *TenderEvaluationCreate) SetTenderID(u uuid.UUID) *TenderEvaluationCreate {
	tec.mutation.SetTenderID(u)
	return tec
}

// SetTenantID sets the "tenant_id" field.
func (tec *TenderEvaluationCreate) SetTenantID(u uuid.UUID) *TenderEvaluationCreate {
	tec.mutation.SetTenantID(u)
	return tec
}

// SetEvaluatorID sets the "evaluator_id" field.
func (tec *TenderEvaluationCreate) SetEvaluatorID(u uuid.UUID) *TenderEvaluationCreate {
	tec.mutation.SetEvaluatorID(u)
	return tec
}

// SetScore sets the "score" field.
func (tec *TenderEvaluationCreate) SetScore(f float64) *TenderEvaluationCreate {
	tec.mutation.SetScore(f)
	return tec
}

// SetNotes sets the "notes" field.
func (tec *TenderEvaluationCreate) SetNotes(s string) *TenderEvaluationCreate {
	tec.mutation.SetNotes(s)
	return tec
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (tec *TenderEvaluationCreate) SetNillableNotes(s *string) *TenderEvaluationCreate {
	if s != nil {
		tec.SetNotes(*s)
	}
	return tec
}

// SetCriteria sets the "criteria" field.
func (tec *TenderEvaluationCreate) SetCriteria(s string) *TenderEvaluationCreate {
	tec.mutation.SetCriteria(s)
	return tec
}

// SetNillableCriteria sets the "criteria" field if the given value is not nil.
func (tec *TenderEvaluationCreate) SetNillableCriteria(s *string) *TenderEvaluationCreate {
	if s != nil {
		tec.SetCriteria(*s)
	}
	return tec
}

// SetEvaluatedAt sets the "evaluated_at" field.
func (tec *TenderEvaluationCreate) SetEvaluatedAt(t time.Time) *TenderEvaluationCreate {
	tec.mutation.SetEvaluatedAt(t)
	return tec
}

// SetNillableEvaluatedAt sets the "evaluated_at" field if the given value is not nil.
func (tec *TenderEvaluationCreate) SetNillableEvaluatedAt(t *time.Time) *TenderEvaluationCreate {
	if t != nil {
		tec.SetEvaluatedAt(*t)
	}
	return tec
}

// SetID sets the "id" field.
func (tec *TenderEvaluationCreate) SetID(u uuid.UUID) *TenderEvaluationCreate {
	tec.mutation.SetID(u)
	return tec
}

// SetNillableID sets the "id" field if the given value is not nil.
func (tec *TenderEvaluationCreate) SetNillableID(u *uuid.UUID) *TenderEvaluationCreate {
	if u != nil {
		tec.SetID(*u)
	}
	return tec
}

// SetTender sets the "tender" edge to the Tender entity.
func (tec *TenderEvaluationCreate) SetTender(t *Tender) *TenderEvaluationCreate {
	return tec.SetTenderID(t.ID)
}

// Mutation returns the TenderEvaluationMutation object of the builder.
func (tec *TenderEvaluationCreate) Mutation() *TenderEvaluationMutation {
	return tec.mutation
}

// Save creates the TenderEvaluation in the database.
func (tec *TenderEvaluationCreate) Save(ctx context.Context) (*TenderEvaluation, error) {
	tec.defaults()
	return withHooks(ctx, tec.sqlSave, tec.mutation, tec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tec *TenderEvaluationCreate) SaveX(ctx context.Context) *TenderEvaluation {
	v, err := tec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tec *TenderEvaluationCreate) Exec(ctx context.Context) error {
	_, err := tec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tec *TenderEvaluationCreate) ExecX(ctx context.Context) {
	if err := tec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tec *TenderEvaluationCreate) defaults() {
	if _, ok := tec.mutation.EvaluatedAt(); !ok {
		v := tenderevaluation.DefaultEvaluatedAt()
		tec.mutation.SetEvaluatedAt(v)
	}
	if _, ok := tec.mutation.ID(); !ok {
		v := tenderevaluation.DefaultID()
		tec.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tec *TenderEvaluationCreate) check() error {
	if _, ok := tec.mutation.TenderID(); !ok {
		return &ValidationError{Name: "tender_id", err: errors.New(`ent: missing required field "TenderEvaluation.tender_id"`)}
	}
	if _, ok := tec.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "TenderEvaluation.tenant_id"`)}
	}
	if _, ok := tec.mutation.EvaluatorID(); !ok {
		return &ValidationError{Name: "evaluator_id", err: errors.New(`ent: missing required field "TenderEvaluation.evaluator_id"`)}
	}
	if _, ok := tec.mutation.Score(); !ok {
		return &ValidationError{Name: "score", err: errors.New(`ent: missing required field "TenderEvaluation.score"`)}
	}
	if _, ok := tec.mutation.EvaluatedAt(); !ok {
		return &ValidationError{Name: "evaluated_at", err: errors.New(`ent: missing required field "TenderEvaluation.evaluated_at"`)}
	}
	if _, ok := tec.mutation.TenderID(); !ok {
		return &ValidationError{Name: "tender", err: errors.New(`ent: missing required edge "TenderEvaluation.tender"`)}
	}
	return nil
}

func (tec *TenderEvaluationCreate) sqlSave(ctx context.Context) (*TenderEvaluation, error) {
	if err := tec.check(); err != nil {
		return nil, err
	}
	_node, _spec := tec.createSpec()
	if err := sqlgraph.CreateNode(ctx, tec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	tec.mutation.id = &_node.ID
	tec.mutation.done = true
	return _node, nil
}

func (tec *TenderEvaluationCreate) createSpec() (*TenderEvaluation, *sqlgraph.CreateSpec) {
	var (
		_node = &TenderEvaluation{config: tec.config}
		_spec = sqlgraph.NewCreateSpec(tenderevaluation.Table, sqlgraph.NewFieldSpec(tenderevaluation.FieldID, field.TypeUUID))
	)
	if id, ok := tec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := tec.mutation.TenantID(); ok {
		_spec.SetField(tenderevaluation.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := tec.mutation.EvaluatorID(); ok {
		_spec.SetField(tenderevaluation.FieldEvaluatorID, field.TypeUUID, value)
		_node.EvaluatorID = value
	}
	if value, ok := tec.mutation.Score(); ok {
		_spec.SetField(tenderevaluation.FieldScore, field.TypeFloat64, value)
		_node.Score = value
	}
	if value, ok := tec.mutation.Notes(); ok {
		_spec.SetField(tenderevaluation.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := tec.mutation.Criteria(); ok {
		_spec.SetField(tenderevaluation.FieldCriteria, field.TypeString, value)
		_node.Criteria = value
	}
	if value, ok := tec.mutation.EvaluatedAt(); ok {
		_spec.SetField(tenderevaluation.FieldEvaluatedAt, field.TypeTime, value)
		_node.EvaluatedAt = value
	}
	if nodes := tec.mutation.TenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenderevaluation.TenderTable,
			Columns: []string{tenderevaluation.TenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tender.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TenderEvaluationCreateBulk is the builder for creating many TenderEvaluation entities in bulk.
type TenderEvaluationCreateBulk struct {
	config
	err      error
	builders []*TenderEvaluationCreate
}

// Save creates the TenderEvaluation entities in the database.
func (tecb *TenderEvaluationCreateBulk) Save(ctx context.Context) ([]*TenderEvaluation, error) {
	if tecb.err != nil {
		return nil, tecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tecb.builders))
	nodes := make([]*TenderEvaluation, len(tecb.builders))
	mutators := make([]Mutator, len(tecb.builders))
	for i := range tecb.builders {
		func(i int, root context.Context) {
			builder := tecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TenderEvaluationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tecb *TenderEvaluationCreateBulk) SaveX(ctx context.Context) []*TenderEvaluation {
	v, err := tecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tecb *TenderEvaluationCreateBulk) Exec(ctx context.Context) error {
	_, err := tecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tecb *TenderEvaluationCreateBulk) ExecX(ctx context.Context) {
	if err := tecb.Exec(ctx); err != nil {
		panic(err)
	}
}
