// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/projects-service/internal/ent/predicate"
	"github.com/bengobox/projects-service/internal/ent/tenderevaluation"
)

// TenderEvaluationDelete is the builder for deleting a TenderEvaluation entity.
type TenderEvaluationDelete struct {
	config
	hooks    []Hook
	mutation *TenderEvaluationMutation
}

// Where appends a list predicates to the TenderEvaluationDelete builder.
func (ted *TenderEvaluationDelete) Where(ps ...predicate.TenderEvaluation) *TenderEvaluationDelete {
	ted.mutation.Where(ps...)
	return ted
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ted *TenderEvaluationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ted.sqlExec, ted.mutation, ted.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ted *TenderEvaluationDelete) ExecX(ctx context.Context) int {
	n, err := ted.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ted *TenderEvaluationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tenderevaluation.Table, sqlgraph.NewFieldSpec(tenderevaluation.FieldID, field.TypeUUID))
	if ps := ted.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ted.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ted.mutation.done = true
	return affected, err
}

// TenderEvaluationDeleteOne is the builder for deleting a single TenderEvaluation entity.
type TenderEvaluationDeleteOne struct {
	ted *TenderEvaluationDelete
}

// Where appends a list predicates to the TenderEvaluationDelete builder.
func (tedo *TenderEvaluationDeleteOne) Where(ps ...predicate.TenderEvaluation) *TenderEvaluationDeleteOne {
	tedo.ted.mutation.Where(ps...)
	return tedo
}

// Exec executes the deletion query.
func (tedo *TenderEvaluationDeleteOne) Exec(ctx context.Context) error {
	n, err := tedo.ted.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tenderevaluation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tedo *TenderEvaluationDeleteOne) ExecX(ctx context.Context) {
	if err := tedo.Exec(ctx); err != nil {
		panic(err)
	}
}
