// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/projects-service/internal/ent/tender"
	"github.com/bengobox/projects-service/internal/ent/tendermeeting"
	"github.com/google/uuid"
)

// TenderMeeting is the model entity for the TenderMeeting schema.
type TenderMeeting struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenderID holds the value of the "tender_id" field.
	TenderID uuid.UUID `json:"tender_id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// ScheduledAt holds the value of the "scheduled_at" field.
	ScheduledAt time.Time `json:"scheduled_at,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// MeetingURL holds the value of the "meeting_url" field.
	MeetingURL string `json:"meeting_url,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy uuid.UUID `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TenderMeetingQuery when eager-loading is set.
	Edges        TenderMeetingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TenderMeetingEdges holds the relations/edges for other nodes in the graph.
type TenderMeetingEdges struct {
	// Tender holds the value of the tender edge.
	Tender *Tender `json:"tender,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TenderOrErr returns the Tender value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TenderMeetingEdges) TenderOrErr() (*Tender, error) {
	if e.Tender != nil {
		return e.Tender, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tender.Label}
	}
	return nil, &NotLoadedError{edge: "tender"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TenderMeeting) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tendermeeting.FieldTitle, tendermeeting.FieldPlatform, tendermeeting.FieldMeetingURL, tendermeeting.FieldNotes:
			values[i] = new(sql.NullString)
		case tendermeeting.FieldScheduledAt, tendermeeting.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case tendermeeting.FieldID, tendermeeting.FieldTenderID, tendermeeting.FieldTenantID, tendermeeting.FieldCreatedBy:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TenderMeeting fields.
func (tm *TenderMeeting) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tendermeeting.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				tm.ID = *value
			}
		case tendermeeting.FieldTenderID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tender_id", values[i])
			} else if value != nil {
				tm.TenderID = *value
			}
		case tendermeeting.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				tm.TenantID = *value
			}
		case tendermeeting.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				tm.Title = value.String
			}
		case tendermeeting.FieldScheduledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field scheduled_at", values[i])
			} else if value.Valid {
				tm.ScheduledAt = value.Time
			}
		case tendermeeting.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				tm.Platform = value.String
			}
		case tendermeeting.FieldMeetingURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field meeting_url", values[i])
			} else if value.Valid {
				tm.MeetingURL = value.String
			}
		case tendermeeting.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				tm.Notes = value.String
			}
		case tendermeeting.FieldCreatedBy:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value != nil {
				tm.CreatedBy = *value
			}
		case tendermeeting.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				tm.CreatedAt = value.Time
			}
		default:
			tm.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TenderMeeting.
// This includes values selected through modifiers, order, etc.
func (tm *TenderMeeting) Value(name string) (ent.Value, error) {
	return tm.selectValues.Get(name)
}

// QueryTender queries the "tender" edge of the TenderMeeting entity.
func (tm *TenderMeeting) QueryTender() *TenderQuery {
	return NewTenderMeetingClient(tm.config).QueryTender(tm)
}

// Update returns a builder for updating this TenderMeeting.
// Note that you need to call TenderMeeting.Unwrap() before calling this method if this TenderMeeting
// was returned from a transaction, and the transaction was committed or rolled back.
func (tm *TenderMeeting) Update() *TenderMeetingUpdateOne {
	return NewTenderMeetingClient(tm.config).UpdateOne(tm)
}

// Unwrap unwraps the TenderMeeting entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tm *TenderMeeting) Unwrap() *TenderMeeting {
	_tx, ok := tm.config.driver.(*txDriver)
	if !ok {
		panic("ent: TenderMeeting is not a transactional entity")
	}
	tm.config.driver = _tx.drv
	return tm
}

// String implements the fmt.Stringer.
func (tm *TenderMeeting) String() string {
	var builder strings.Builder
	builder.WriteString("TenderMeeting(")
	builder.WriteString(fmt.Sprintf("id=%v, ", tm.ID))
	builder.WriteString("tender_id=")
	builder.WriteString(fmt.Sprintf("%v", tm.TenderID))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", tm.TenantID))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(tm.Title)
	builder.WriteString(", ")
	builder.WriteString("scheduled_at=")
	builder.WriteString(tm.ScheduledAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(tm.Platform)
	builder.WriteString(", ")
	builder.WriteString("meeting_url=")
	builder.WriteString(tm.MeetingURL)
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(tm.Notes)
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", tm.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(tm.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TenderMeetings is a parsable slice of TenderMeeting.
type TenderMeetings []*TenderMeeting
