// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/projects-service/internal/ent/predicate"
	"github.com/bengobox/projects-service/internal/ent/tender"
	"github.com/bengobox/projects-service/internal/ent/tenderdocument"
	"github.com/google/uuid"
)

// TenderDocumentUpdate is the builder for updating TenderDocument entities.
type TenderDocumentUpdate struct {
	config
	hooks    []Hook
	mutation *TenderDocumentMutation
}

// Where appends a list predicates to the TenderDocumentUpdate builder.
func (tdu *TenderDocumentUpdate) Where(ps ...predicate.TenderDocument) *TenderDocumentUpdate {
	tdu.mutation.Where(ps...)
	return tdu
}

// SetTenderID sets the "tender_id" field.
func (tdu *TenderDocumentUpdate) SetTenderID(u uuid.UUID) *TenderDocumentUpdate {
	tdu.mutation.SetTenderID(u)
	return tdu
}

// SetNillableTenderID sets the "tender_id" field if the given value is not nil.
func (tdu *TenderDocumentUpdate) SetNillableTenderID(u *uuid.UUID) *TenderDocumentUpdate {
	if u != nil {
		tdu.SetTenderID(*u)
	}
	return tdu
}

// SetTenantID sets the "tenant_id" field.
func (tdu *TenderDocumentUpdate) SetTenantID(u uuid.UUID) *TenderDocumentUpdate {
	tdu.mutation.SetTenantID(u)
	return tdu
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (tdu *TenderDocumentUpdate) SetNillableTenantID(u *uuid.UUID) *TenderDocumentUpdate {
	if u != nil {
		tdu.SetTenantID(*u)
	}
	return tdu
}

// SetFileURL sets the "file_url" field.
func (tdu *TenderDocumentUpdate) SetFileURL(s string) *TenderDocumentUpdate {
	tdu.mutation.SetFileURL(s)
	return tdu
}

// SetNillableFileURL sets the "file_url" field if the given value is not nil.
func (tdu *TenderDocumentUpdate) SetNillableFileURL(s *string) *TenderDocumentUpdate {
	if s != nil {
		tdu.SetFileURL(*s)
	}
	return tdu
}

// SetFileName sets the "file_name" field.
func (tdu *TenderDocumentUpdate) SetFileName(s string) *TenderDocumentUpdate {
	tdu.mutation.SetFileName(s)
	return tdu
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (tdu *TenderDocumentUpdate) SetNillableFileName(s *string) *TenderDocumentUpdate {
	if s != nil {
		tdu.SetFileName(*s)
	}
	return tdu
}

// SetFileSize sets the "file_size" field.
func (tdu *TenderDocumentUpdate) SetFileSize(i int64) *TenderDocumentUpdate {
	tdu.mutation.ResetFileSize()
	tdu.mutation.SetFileSize(i)
	return tdu
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (tdu *TenderDocumentUpdate) SetNillableFileSize(i *int64) *TenderDocumentUpdate {
	if i != nil {
		tdu.SetFileSize(*i)
	}
	return tdu
}

// AddFileSize adds i to the "file_size" field.
func (tdu *TenderDocumentUpdate) AddFileSize(i int64) *TenderDocumentUpdate {
	tdu.mutation.AddFileSize(i)
	return tdu
}

// ClearFileSize clears the value of the "file_size" field.
func (tdu *TenderDocumentUpdate) ClearFileSize() *TenderDocumentUpdate {
	tdu.mutation.ClearFileSize()
	return tdu
}

// SetMimeType sets the "mime_type" field.
func (tdu *TenderDocumentUpdate) SetMimeType(s string) *TenderDocumentUpdate {
	tdu.mutation.SetMimeType(s)
	return tdu
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (tdu *TenderDocumentUpdate) SetNillableMimeType(s *string) *TenderDocumentUpdate {
	if s != nil {
		tdu.SetMimeType(*s)
	}
	return tdu
}

// ClearMimeType clears the value of the "mime_type" field.
func (tdu *TenderDocumentUpdate) ClearMimeType() *TenderDocumentUpdate {
	tdu.mutation.ClearMimeType()
	return tdu
}

// SetUploadedBy sets the "uploaded_by" field.
func (tdu *TenderDocumentUpdate) SetUploadedBy(u uuid.UUID) *TenderDocumentUpdate {
	tdu.mutation.SetUploadedBy(u)
	return tdu
}

// SetNillableUploadedBy sets the "uploaded_by" field if the given value is not nil.
func (tdu *TenderDocumentUpdate) SetNillableUploadedBy(u *uuid.UUID) *TenderDocumentUpdate {
	if u != nil {
		tdu.SetUploadedBy(*u)
	}
	return tdu
}

// SetTender sets the "tender" edge to the Tender entity.
func (tdu *TenderDocumentUpdate) SetTender(t *Tender) *TenderDocumentUpdate {
	return tdu.SetTenderID(t.ID)
}

// Mutation returns the TenderDocumentMutation object of the builder.
func (tdu *TenderDocumentUpdate) Mutation() *TenderDocumentMutation {
	return tdu.mutation
}

// ClearTender clears the "tender" edge to the Tender entity.
func (tdu *TenderDocumentUpdate) ClearTender() *TenderDocumentUpdate {
	tdu.mutation.ClearTender()
	return tdu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tdu *TenderDocumentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tdu.sqlSave, tdu.mutation, tdu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tdu *TenderDocumentUpdate) SaveX(ctx context.Context) int {
	affected, err := tdu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tdu *TenderDocumentUpdate) Exec(ctx context.Context) error {
	_, err := tdu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tdu *TenderDocumentUpdate) ExecX(ctx context.Context) {
	if err := tdu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tdu *TenderDocumentUpdate) check() error {
	if _, ok := tdu.mutation.TenderID(); tdu.mutation.TenderCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "TenderDocument.tender"`)
	}
	return nil
}

func (tdu *TenderDocumentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tdu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenderdocument.Table, tenderdocument.Columns, sqlgraph.NewFieldSpec(tenderdocument.FieldID, field.TypeUUID))
	if ps := tdu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tdu.mutation.TenantID(); ok {
		_spec.SetField(tenderdocument.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := tdu.mutation.FileURL(); ok {
		_spec.SetField(tenderdocument.FieldFileURL, field.TypeString, value)
	}
	if value, ok := tdu.mutation.FileName(); ok {
		_spec.SetField(tenderdocument.FieldFileName, field.TypeString, value)
	}
	if value, ok := tdu.mutation.FileSize(); ok {
		_spec.SetField(tenderdocument.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := tdu.mutation.AddedFileSize(); ok {
		_spec.AddField(tenderdocument.FieldFileSize, field.TypeInt64, value)
	}
	if tdu.mutation.FileSizeCleared() {
		_spec.ClearField(tenderdocument.FieldFileSize, field.TypeInt64)
	}
	if value, ok := tdu.mutation.MimeType(); ok {
		_spec.SetField(tenderdocument.FieldMimeType, field.TypeString, value)
	}
	if tdu.mutation.MimeTypeCleared() {
		_spec.ClearField(tenderdocument.FieldMimeType, field.TypeString)
	}
	if value, ok := tdu.mutation.UploadedBy(); ok {
		_spec.SetField(tenderdocument.FieldUploadedBy, field.TypeUUID, value)
	}
	if tdu.mutation.TenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenderdocument.TenderTable,
			Columns: []string{tenderdocument.TenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tender.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tdu.mutation.TenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenderdocument.TenderTable,
			Columns: []string{tenderdocument.TenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tender.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tdu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenderdocument.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tdu.mutation.done = true
	return n, nil
}

// TenderDocumentUpdateOne is the builder for updating a single TenderDocument entity.
type TenderDocumentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenderDocumentMutation
}

// SetTenderID sets the "tender_id" field.
func (tduo *TenderDocumentUpdateOne) SetTenderID(u uuid.UUID) *TenderDocumentUpdateOne {
	tduo.mutation.SetTenderID(u)
	return tduo
}

// SetNillableTenderID sets the "tender_id" field if the given value is not nil.
func (tduo *TenderDocumentUpdateOne) SetNillableTenderID(u *uuid.UUID) *TenderDocumentUpdateOne {
	if u != nil {
		tduo.SetTenderID(*u)
	}
	return tduo
}

// SetTenantID sets the "tenant_id" field.
func (tduo *TenderDocumentUpdateOne) SetTenantID(u uuid.UUID) *TenderDocumentUpdateOne {
	tduo.mutation.SetTenantID(u)
	return tduo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (tduo *TenderDocumentUpdateOne) SetNillableTenantID(u *uuid.UUID) *TenderDocumentUpdateOne {
	if u != nil {
		tduo.SetTenantID(*u)
	}
	return tduo
}

// SetFileURL sets the "file_url" field.
func (tduo *TenderDocumentUpdateOne) SetFileURL(s string) *TenderDocumentUpdateOne {
	tduo.mutation.SetFileURL(s)
	return tduo
}

// SetNillableFileURL sets the "file_url" field if the given value is not nil.
func (tduo *TenderDocumentUpdateOne) SetNillableFileURL(s *string) *TenderDocumentUpdateOne {
	if s != nil {
		tduo.SetFileURL(*s)
	}
	return tduo
}

// SetFileName sets the "file_name" field.
func (tduo *TenderDocumentUpdateOne) SetFileName(s string) *TenderDocumentUpdateOne {
	tduo.mutation.SetFileName(s)
	return tduo
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (tduo *TenderDocumentUpdateOne) SetNillableFileName(s *string) *TenderDocumentUpdateOne {
	if s != nil {
		tduo.SetFileName(*s)
	}
	return tduo
}

// SetFileSize sets the "file_size" field.
func (tduo *TenderDocumentUpdateOne) SetFileSize(i int64) *TenderDocumentUpdateOne {
	tduo.mutation.ResetFileSize()
	tduo.mutation.SetFileSize(i)
	return tduo
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (tduo *TenderDocumentUpdateOne) SetNillableFileSize(i *int64) *TenderDocumentUpdateOne {
	if i != nil {
		tduo.SetFileSize(*i)
	}
	return tduo
}

// AddFileSize adds i to the "file_size" field.
func (tduo *TenderDocumentUpdateOne) AddFileSize(i int64) *TenderDocumentUpdateOne {
	tduo.mutation.AddFileSize(i)
	return tduo
}

// ClearFileSize clears the value of the "file_size" field.
func (tduo *TenderDocumentUpdateOne) ClearFileSize() *TenderDocumentUpdateOne {
	tduo.mutation.ClearFileSize()
	return tduo
}

// SetMimeType sets the "mime_type" field.
func (tduo *TenderDocumentUpdateOne) SetMimeType(s string) *TenderDocumentUpdateOne {
	tduo.mutation.SetMimeType(s)
	return tduo
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (tduo *TenderDocumentUpdateOne) SetNillableMimeType(s *string) *TenderDocumentUpdateOne {
	if s != nil {
		tduo.SetMimeType(*s)
	}
	return tduo
}

// ClearMimeType clears the value of the "mime_type" field.
func (tduo *TenderDocumentUpdateOne) ClearMimeType() *TenderDocumentUpdateOne {
	tduo.mutation.ClearMimeType()
	return tduo
}

// SetUploadedBy sets the "uploaded_by" field.
func (tduo *TenderDocumentUpdateOne) SetUploadedBy(u uuid.UUID) *TenderDocumentUpdateOne {
	tduo.mutation.SetUploadedBy(u)
	return tduo
}

// SetNillableUploadedBy sets the "uploaded_by" field if the given value is not nil.
func (tduo *TenderDocumentUpdateOne) SetNillableUploadedBy(u *uuid.UUID) *TenderDocumentUpdateOne {
	if u != nil {
		tduo.SetUploadedBy(*u)
	}
	return tduo
}

// SetTender sets the "tender" edge to the Tender entity.
func (tduo *TenderDocumentUpdateOne) SetTender(t *Tender) *TenderDocumentUpdateOne {
	return tduo.SetTenderID(t.ID)
}

// Mutation returns the TenderDocumentMutation object of the builder.
func (tduo *TenderDocumentUpdateOne) Mutation() *TenderDocumentMutation {
	return tduo.mutation
}

// ClearTender clears the "tender" edge to the Tender entity.
func (tduo *TenderDocumentUpdateOne) ClearTender() *TenderDocumentUpdateOne {
	tduo.mutation.ClearTender()
	return tduo
}

// Where appends a list predicates to the TenderDocumentUpdate builder.
func (tduo *TenderDocumentUpdateOne) Where(ps ...predicate.TenderDocument) *TenderDocumentUpdateOne {
	tduo.mutation.Where(ps...)
	return tduo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tduo *TenderDocumentUpdateOne) Select(field string, fields ...string) *TenderDocumentUpdateOne {
	tduo.fields = append([]string{field}, fields...)
	return tduo
}

// Save executes the query and returns the updated TenderDocument entity.
func (tduo *TenderDocumentUpdateOne) Save(ctx context.Context) (*TenderDocument, error) {
	return withHooks(ctx, tduo.sqlSave, tduo.mutation, tduo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tduo *TenderDocumentUpdateOne) SaveX(ctx context.Context) *TenderDocument {
	node, err := tduo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tduo *TenderDocumentUpdateOne) Exec(ctx context.Context) error {
	_, err := tduo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tduo *TenderDocumentUpdateOne) ExecX(ctx context.Context) {
	if err := tduo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tduo *TenderDocumentUpdateOne) check() error {
	if _, ok := tduo.mutation.TenderID(); tduo.mutation.TenderCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "TenderDocument.tender"`)
	}
	return nil
}

func (tduo *TenderDocumentUpdateOne) sqlSave(ctx context.Context) (_node *TenderDocument, err error) {
	if err := tduo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenderdocument.Table, tenderdocument.Columns, sqlgraph.NewFieldSpec(tenderdocument.FieldID, field.TypeUUID))
	id, ok := tduo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TenderDocument.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tduo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenderdocument.FieldID)
		for _, f := range fields {
			if !tenderdocument.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenderdocument.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tduo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tduo.mutation.TenantID(); ok {
		_spec.SetField(tenderdocument.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := tduo.mutation.FileURL(); ok {
		_spec.SetField(tenderdocument.FieldFileURL, field.TypeString, value)
	}
	if value, ok := tduo.mutation.FileName(); ok {
		_spec.SetField(tenderdocument.FieldFileName, field.TypeString, value)
	}
	if value, ok := tduo.mutation.FileSize(); ok {
		_spec.SetField(tenderdocument.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := tduo.mutation.AddedFileSize(); ok {
		_spec.AddField(tenderdocument.FieldFileSize, field.TypeInt64, value)
	}
	if tduo.mutation.FileSizeCleared() {
		_spec.ClearField(tenderdocument.FieldFileSize, field.TypeInt64)
	}
	if value, ok := tduo.mutation.MimeType(); ok {
		_spec.SetField(tenderdocument.FieldMimeType, field.TypeString, value)
	}
	if tduo.mutation.MimeTypeCleared() {
		_spec.ClearField(tenderdocument.FieldMimeType, field.TypeString)
	}
	if value, ok := tduo.mutation.UploadedBy(); ok {
		_spec.SetField(tenderdocument.FieldUploadedBy, field.TypeUUID, value)
	}
	if tduo.mutation.TenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenderdocument.TenderTable,
			Columns: []string{tenderdocument.TenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tender.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tduo.mutation.TenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenderdocument.TenderTable,
			Columns: []string{tenderdocument.TenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tender.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TenderDocument{config: tduo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tduo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenderdocument.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tduo.mutation.done = true
	return _node, nil
}
