// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/projects-service/internal/ent/tender"
	"github.com/bengobox/projects-service/internal/ent/tendercommittee"
	"github.com/google/uuid"
)

// TenderCommittee is the model entity for the TenderCommittee schema.
type TenderCommittee struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenderID holds the value of the "tender_id" field.
	TenderID uuid.UUID `json:"tender_id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TenderCommitteeQuery when eager-loading is set.
	Edges        TenderCommitteeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TenderCommitteeEdges holds the relations/edges for other nodes in the graph.
type TenderCommitteeEdges struct {
	// Tender holds the value of the tender edge.
	Tender *Tender `json:"tender,omitempty"`
	// Members holds the value of the members edge.
	Members []*TenderCommitteeMember `json:"members,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TenderOrErr returns the Tender value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TenderCommitteeEdges) TenderOrErr() (*Tender, error) {
	if e.Tender != nil {
		return e.Tender, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tender.Label}
	}
	return nil, &NotLoadedError{edge: "tender"}
}

// MembersOrErr returns the Members value or an error if the edge
// was not loaded in eager-loading.
func (e TenderCommitteeEdges) MembersOrErr() ([]*TenderCommitteeMember, error) {
	if e.loadedTypes[1] {
		return e.Members, nil
	}
	return nil, &NotLoadedError{edge: "members"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TenderCommittee) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tendercommittee.FieldName:
			values[i] = new(sql.NullString)
		case tendercommittee.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case tendercommittee.FieldID, tendercommittee.FieldTenderID, tendercommittee.FieldTenantID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TenderCommittee fields.
func (tc *TenderCommittee) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tendercommittee.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				tc.ID = *value
			}
		case tendercommittee.FieldTenderID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tender_id", values[i])
			} else if value != nil {
				tc.TenderID = *value
			}
		case tendercommittee.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				tc.TenantID = *value
			}
		case tendercommittee.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				tc.Name = value.String
			}
		case tendercommittee.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				tc.CreatedAt = value.Time
			}
		default:
			tc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TenderCommittee.
// This includes values selected through modifiers, order, etc.
func (tc *TenderCommittee) Value(name string) (ent.Value, error) {
	return tc.selectValues.Get(name)
}

// QueryTender queries the "tender" edge of the TenderCommittee entity.
func (tc *TenderCommittee) QueryTender() *TenderQuery {
	return NewTenderCommitteeClient(tc.config).QueryTender(tc)
}

// QueryMembers queries the "members" edge of the TenderCommittee entity.
func (tc *TenderCommittee) QueryMembers() *TenderCommitteeMemberQuery {
	return NewTenderCommitteeClient(tc.config).QueryMembers(tc)
}

// Update returns a builder for updating this TenderCommittee.
// Note that you need to call TenderCommittee.Unwrap() before calling this method if this TenderCommittee
// was returned from a transaction, and the transaction was committed or rolled back.
func (tc *TenderCommittee) Update() *TenderCommitteeUpdateOne {
	return NewTenderCommitteeClient(tc.config).UpdateOne(tc)
}

// Unwrap unwraps the TenderCommittee entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tc *TenderCommittee) Unwrap() *TenderCommittee {
	_tx, ok := tc.config.driver.(*txDriver)
	if !ok {
		panic("ent: TenderCommittee is not a transactional entity")
	}
	tc.config.driver = _tx.drv
	return tc
}

// String implements the fmt.Stringer.
func (tc *TenderCommittee) String() string {
	var builder strings.Builder
	builder.WriteString("TenderCommittee(")
	builder.WriteString(fmt.Sprintf("id=%v, ", tc.ID))
	builder.WriteString("tender_id=")
	builder.WriteString(fmt.Sprintf("%v", tc.TenderID))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", tc.TenantID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(tc.Name)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(tc.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TenderCommittees is a parsable slice of TenderCommittee.
type TenderCommittees []*TenderCommittee
