// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/projects-service/internal/ent/predicate"
	"github.com/bengobox/projects-service/internal/ent/tender"
	"github.com/bengobox/projects-service/internal/ent/tendermeeting"
	"github.com/google/uuid"
)

// TenderMeetingQuery is the builder for querying TenderMeeting entities.
type TenderMeetingQuery struct {
	config
	ctx        *QueryContext
	order      []tendermeeting.OrderOption
	inters     []Interceptor
	predicates []predicate.TenderMeeting
	withTender *TenderQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TenderMeetingQuery builder.
func (tmq *TenderMeetingQuery) Where(ps ...predicate.TenderMeeting) *TenderMeetingQuery {
	tmq.predicates = append(tmq.predicates, ps...)
	return tmq
}

// Limit the number of records to be returned by this query.
func (tmq *TenderMeetingQuery) Limit(limit int) *TenderMeetingQuery {
	tmq.ctx.Limit = &limit
	return tmq
}

// Offset to start from.
func (tmq *TenderMeetingQuery) Offset(offset int) *TenderMeetingQuery {
	tmq.ctx.Offset = &offset
	return tmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tmq *TenderMeetingQuery) Unique(unique bool) *TenderMeetingQuery {
	tmq.ctx.Unique = &unique
	return tmq
}

// Order specifies how the records should be ordered.
func (tmq *TenderMeetingQuery) Order(o ...tendermeeting.OrderOption) *TenderMeetingQuery {
	tmq.order = append(tmq.order, o...)
	return tmq
}

// QueryTender chains the current query on the "tender" edge.
func (tmq *TenderMeetingQuery) QueryTender() *TenderQuery {
	query := (&TenderClient{config: tmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tendermeeting.Table, tendermeeting.FieldID, selector),
			sqlgraph.To(tender.Table, tender.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, tendermeeting.TenderTable, tendermeeting.TenderColumn),
		)
		fromU = sqlgraph.SetNeighbors(tmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TenderMeeting entity from the query.
// Returns a *NotFoundError when no TenderMeeting was found.
func (tmq *TenderMeetingQuery) First(ctx context.Context) (*TenderMeeting, error) {
	nodes, err := tmq.Limit(1).All(setContextOp(ctx, tmq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tendermeeting.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tmq *TenderMeetingQuery) FirstX(ctx context.Context) *TenderMeeting {
	node, err := tmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TenderMeeting ID from the query.
// Returns a *NotFoundError when no TenderMeeting ID was found.
func (tmq *TenderMeetingQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tmq.Limit(1).IDs(setContextOp(ctx, tmq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tendermeeting.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tmq *TenderMeetingQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := tmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TenderMeeting entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TenderMeeting entity is found.
// Returns a *NotFoundError when no TenderMeeting entities are found.
func (tmq *TenderMeetingQuery) Only(ctx context.Context) (*TenderMeeting, error) {
	nodes, err := tmq.Limit(2).All(setContextOp(ctx, tmq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tendermeeting.Label}
	default:
		return nil, &NotSingularError{tendermeeting.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tmq *TenderMeetingQuery) OnlyX(ctx context.Context) *TenderMeeting {
	node, err := tmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TenderMeeting ID in the query.
// Returns a *NotSingularError when more than one TenderMeeting ID is found.
// Returns a *NotFoundError when no entities are found.
func (tmq *TenderMeetingQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tmq.Limit(2).IDs(setContextOp(ctx, tmq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tendermeeting.Label}
	default:
		err = &NotSingularError{tendermeeting.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tmq *TenderMeetingQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := tmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TenderMeetings.
func (tmq *TenderMeetingQuery) All(ctx context.Context) ([]*TenderMeeting, error) {
	ctx = setContextOp(ctx, tmq.ctx, "All")
	if err := tmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TenderMeeting, *TenderMeetingQuery]()
	return withInterceptors[[]*TenderMeeting](ctx, tmq, qr, tmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tmq *TenderMeetingQuery) AllX(ctx context.Context) []*TenderMeeting {
	nodes, err := tmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TenderMeeting IDs.
func (tmq *TenderMeetingQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if tmq.ctx.Unique == nil && tmq.path != nil {
		tmq.Unique(true)
	}
	ctx = setContextOp(ctx, tmq.ctx, "IDs")
	if err = tmq.Select(tendermeeting.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tmq *TenderMeetingQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := tmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tmq *TenderMeetingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tmq.ctx, "Count")
	if err := tmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tmq, querierCount[*TenderMeetingQuery](), tmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tmq *TenderMeetingQuery) CountX(ctx context.Context) int {
	count, err := tmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tmq *TenderMeetingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tmq.ctx, "Exist")
	switch _, err := tmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tmq *TenderMeetingQuery) ExistX(ctx context.Context) bool {
	exist, err := tmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TenderMeetingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tmq *TenderMeetingQuery) Clone() *TenderMeetingQuery {
	if tmq == nil {
		return nil
	}
	return &TenderMeetingQuery{
		config:     tmq.config,
		ctx:        tmq.ctx.Clone(),
		order:      append([]tendermeeting.OrderOption{}, tmq.order...),
		inters:     append([]Interceptor{}, tmq.inters...),
		predicates: append([]predicate.TenderMeeting{}, tmq.predicates...),
		withTender: tmq.withTender.Clone(),
		// clone intermediate query.
		sql:  tmq.sql.Clone(),
		path: tmq.path,
	}
}

// WithTender tells the query-builder to eager-load the nodes that are connected to
// the "tender" edge. The optional arguments are used to configure the query builder of the edge.
func (tmq *TenderMeetingQuery) WithTender(opts ...func(*TenderQuery)) *TenderMeetingQuery {
	query := (&TenderClient{config: tmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tmq.withTender = query
	return tmq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenderID uuid.UUID `json:"tender_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TenderMeeting.Query().
//		GroupBy(tendermeeting.FieldTenderID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tmq *TenderMeetingQuery) GroupBy(field string, fields ...string) *TenderMeetingGroupBy {
	tmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TenderMeetingGroupBy{build: tmq}
	grbuild.flds = &tmq.ctx.Fields
	grbuild.label = tendermeeting.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenderID uuid.UUID `json:"tender_id,omitempty"`
//	}
//
//	client.TenderMeeting.Query().
//		Select(tendermeeting.FieldTenderID).
//		Scan(ctx, &v)
func (tmq *TenderMeetingQuery) Select(fields ...string) *TenderMeetingSelect {
	tmq.ctx.Fields = append(tmq.ctx.Fields, fields...)
	sbuild := &TenderMeetingSelect{TenderMeetingQuery: tmq}
	sbuild.label = tendermeeting.Label
	sbuild.flds, sbuild.scan = &tmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TenderMeetingSelect configured with the given aggregations.
func (tmq *TenderMeetingQuery) Aggregate(fns ...AggregateFunc) *TenderMeetingSelect {
	return tmq.Select().Aggregate(fns...)
}

func (tmq *TenderMeetingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tmq); err != nil {
				return err
			}
		}
	}
	for _, f := range tmq.ctx.Fields {
		if !tendermeeting.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tmq.path != nil {
		prev, err := tmq.path(ctx)
		if err != nil {
			return err
		}
		tmq.sql = prev
	}
	return nil
}

func (tmq *TenderMeetingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TenderMeeting, error) {
	var (
		nodes       = []*TenderMeeting{}
		_spec       = tmq.querySpec()
		loadedTypes = [1]bool{
			tmq.withTender != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TenderMeeting).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TenderMeeting{config: tmq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tmq.withTender; query != nil {
		if err := tmq.loadTender(ctx, query, nodes, nil,
			func(n *TenderMeeting, e *Tender) { n.Edges.Tender = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tmq *TenderMeetingQuery) loadTender(ctx context.Context, query *TenderQuery, nodes []*TenderMeeting, init func(*TenderMeeting), assign func(*TenderMeeting, *Tender)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*TenderMeeting)
	for i := range nodes {
		fk := nodes[i].TenderID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tender.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "tender_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tmq *TenderMeetingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tmq.querySpec()
	_spec.Node.Columns = tmq.ctx.Fields
	if len(tmq.ctx.Fields) > 0 {
		_spec.Unique = tmq.ctx.Unique != nil && *tmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tmq.driver, _spec)
}

func (tmq *TenderMeetingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tendermeeting.Table, tendermeeting.Columns, sqlgraph.NewFieldSpec(tendermeeting.FieldID, field.TypeUUID))
	_spec.From = tmq.sql
	if unique := tmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tmq.path != nil {
		_spec.Unique = true
	}
	if fields := tmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tendermeeting.FieldID)
		for i := range fields {
			if fields[i] != tendermeeting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if tmq.withTender != nil {
			_spec.Node.AddColumnOnce(tendermeeting.FieldTenderID)
		}
	}
	if ps := tmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tmq *TenderMeetingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tmq.driver.Dialect())
	t1 := builder.Table(tendermeeting.Table)
	columns := tmq.ctx.Fields
	if len(columns) == 0 {
		columns = tendermeeting.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tmq.sql != nil {
		selector = tmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tmq.ctx.Unique != nil && *tmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tmq.predicates {
		p(selector)
	}
	for _, p := range tmq.order {
		p(selector)
	}
	if offset := tmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TenderMeetingGroupBy is the group-by builder for TenderMeeting entities.
type TenderMeetingGroupBy struct {
	selector
	build *TenderMeetingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tmgb *TenderMeetingGroupBy) Aggregate(fns ...AggregateFunc) *TenderMeetingGroupBy {
	tmgb.fns = append(tmgb.fns, fns...)
	return tmgb
}

// Scan applies the selector query and scans the result into the given value.
func (tmgb *TenderMeetingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tmgb.build.ctx, "GroupBy")
	if err := tmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TenderMeetingQuery, *TenderMeetingGroupBy](ctx, tmgb.build, tmgb, tmgb.build.inters, v)
}

func (tmgb *TenderMeetingGroupBy) sqlScan(ctx context.Context, root *TenderMeetingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tmgb.fns))
	for _, fn := range tmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tmgb.flds)+len(tmgb.fns))
		for _, f := range *tmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TenderMeetingSelect is the builder for selecting fields of TenderMeeting entities.
type TenderMeetingSelect struct {
	*TenderMeetingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tms *TenderMeetingSelect) Aggregate(fns ...AggregateFunc) *TenderMeetingSelect {
	tms.fns = append(tms.fns, fns...)
	return tms
}

// Scan applies the selector query and scans the result into the given value.
func (tms *TenderMeetingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tms.ctx, "Select")
	if err := tms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TenderMeetingQuery, *TenderMeetingSelect](ctx, tms.TenderMeetingQuery, tms, tms.inters, v)
}

func (tms *TenderMeetingSelect) sqlScan(ctx context.Context, root *TenderMeetingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tms.fns))
	for _, fn := range tms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
