// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/projects-service/internal/ent/tender"
	"github.com/bengobox/projects-service/internal/ent/tenderdocument"
	"github.com/google/uuid"
)

// TenderDocumentCreate is the builder for creating a TenderDocument entity.
type TenderDocumentCreate struct {
	config
	mutation *TenderDocumentMutation
	hooks    []Hook
}

// SetTenderID sets the "tender_id" field.
func (tdc *TenderDocumentCreate) SetTenderID(u uuid.UUID) *TenderDocumentCreate {
	tdc.mutation.SetTenderID(u)
	return tdc
}

// SetTenantID sets the "tenant_id" field.
func (tdc *TenderDocumentCreate) SetTenantID(u uuid.UUID) *TenderDocumentCreate {
	tdc.mutation.SetTenantID(u)
	return tdc
}

// SetFileURL sets the "file_url" field.
func (tdc *TenderDocumentCreate) SetFileURL(s string) *TenderDocumentCreate {
	tdc.mutation.SetFileURL(s)
	return tdc
}

// SetFileName sets the "file_name" field.
func (tdc *TenderDocumentCreate) SetFileName(s string) *TenderDocumentCreate {
	tdc.mutation.SetFileName(s)
	return tdc
}

// SetFileSize sets the "file_size" field.
func (tdc *TenderDocumentCreate) SetFileSize(i int64) *TenderDocumentCreate {
	tdc.mutation.SetFileSize(i)
	return tdc
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (tdc *TenderDocumentCreate) SetNillableFileSize(i *int64) *TenderDocumentCreate {
	if i != nil {
		tdc.SetFileSize(*i)
	}
	return tdc
}

// SetMimeType sets the "mime_type" field.
func (tdc *TenderDocumentCreate) SetMimeType(s string) *TenderDocumentCreate {
	tdc.mutation.SetMimeType(s)
	return tdc
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (tdc *TenderDocumentCreate) SetNillableMimeType(s *string) *TenderDocumentCreate {
	if s != nil {
		tdc.SetMimeType(*s)
	}
	return tdc
}

// SetUploadedBy sets the "uploaded_by" field.
func (tdc *TenderDocumentCreate) SetUploadedBy(u uuid.UUID) *TenderDocumentCreate {
	tdc.mutation.SetUploadedBy(u)
	return tdc
}

// SetUploadedAt sets the "uploaded_at" field.
func (tdc *TenderDocumentCreate) SetUploadedAt(t time.Time) *TenderDocumentCreate {
	tdc.mutation.SetUploadedAt(t)
	return tdc
}

// SetNillableUploadedAt sets the "uploaded_at" field if the given value is not nil.
func (tdc *TenderDocumentCreate) SetNillableUploadedAt(t *time.Time) *TenderDocumentCreate {
	if t != nil {
		tdc.SetUploadedAt(*t)
	}
	return tdc
}

// SetID sets the "id" field.
func (tdc *TenderDocumentCreate) SetID(u uuid.UUID) *TenderDocumentCreate {
	tdc.mutation.SetID(u)
	return tdc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (tdc *TenderDocumentCreate) SetNillableID(u *uuid.UUID) *TenderDocumentCreate {
	if u != nil {
		tdc.SetID(*u)
	}
	return tdc
}

// SetTender sets the "tender" edge to the Tender entity.
func (tdc *TenderDocumentCreate) SetTender(t *Tender) *TenderDocumentCreate {
	return tdc.SetTenderID(t.ID)
}

// Mutation returns the TenderDocumentMutation object of the builder.
func (tdc *TenderDocumentCreate) Mutation() *TenderDocumentMutation {
	return tdc.mutation
}

// Save creates the TenderDocument in the database.
func (tdc *TenderDocumentCreate) Save(ctx context.Context) (*TenderDocument, error) {
	tdc.defaults()
	return withHooks(ctx, tdc.sqlSave, tdc.mutation, tdc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tdc *TenderDocumentCreate) SaveX(ctx context.Context) *TenderDocument {
	v, err := tdc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tdc *TenderDocumentCreate) Exec(ctx context.Context) error {
	_, err := tdc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tdc *TenderDocumentCreate) ExecX(ctx context.Context) {
	if err := tdc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tdc *TenderDocumentCreate) defaults() {
	if _, ok := tdc.mutation.UploadedAt(); !ok {
		v := tenderdocument.DefaultUploadedAt()
		tdc.mutation.SetUploadedAt(v)
	}
	if _, ok := tdc.mutation.ID(); !ok {
		v := tenderdocument.DefaultID()
		tdc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tdc *TenderDocumentCreate) check() error {
	if _, ok := tdc.mutation.TenderID(); !ok {
		return &ValidationError{Name: "tender_id", err: errors.New(`ent: missing required field "TenderDocument.tender_id"`)}
	}
	if _, ok := tdc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "TenderDocument.tenant_id"`)}
	}
	if _, ok := tdc.mutation.FileURL(); !ok {
		return &ValidationError{Name: "file_url", err: errors.New(`ent: missing required field "TenderDocument.file_url"`)}
	}
	if _, ok := tdc.mutation.FileName(); !ok {
		return &ValidationError{Name: "file_name", err: errors.New(`ent: missing required field "TenderDocument.file_name"`)}
	}
	if _, ok := tdc.mutation.UploadedBy(); !ok {
		return &ValidationError{Name: "uploaded_by", err: errors.New(`ent: missing required field "TenderDocument.uploaded_by"`)}
	}
	if _, ok := tdc.mutation.UploadedAt(); !ok {
		return &ValidationError{Name: "uploaded_at", err: errors.New(`ent: missing required field "TenderDocument.uploaded_at"`)}
	}
	if _, ok := tdc.mutation.TenderID(); !ok {
		return &ValidationError{Name: "tender", err: errors.New(`ent: missing required edge "TenderDocument.tender"`)}
	}
	return nil
}

func (tdc *TenderDocumentCreate) sqlSave(ctx context.Context) (*TenderDocument, error) {
	if err := tdc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tdc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tdc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	tdc.mutation.id = &_node.ID
	tdc.mutation.done = true
	return _node, nil
}

func (tdc *TenderDocumentCreate) createSpec() (*TenderDocument, *sqlgraph.CreateSpec) {
	var (
		_node = &TenderDocument{config: tdc.config}
		_spec = sqlgraph.NewCreateSpec(tenderdocument.Table, sqlgraph.NewFieldSpec(tenderdocument.FieldID, field.TypeUUID))
	)
	if id, ok := tdc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := tdc.mutation.TenantID(); ok {
		_spec.SetField(tenderdocument.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := tdc.mutation.FileURL(); ok {
		_spec.SetField(tenderdocument.FieldFileURL, field.TypeString, value)
		_node.FileURL = value
	}
	if value, ok := tdc.mutation.FileName(); ok {
		_spec.SetField(tenderdocument.FieldFileName, field.TypeString, value)
		_node.FileName = value
	}
	if value, ok := tdc.mutation.FileSize(); ok {
		_spec.SetField(tenderdocument.FieldFileSize, field.TypeInt64, value)
		_node.FileSize = value
	}
	if value, ok := tdc.mutation.MimeType(); ok {
		_spec.SetField(tenderdocument.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := tdc.mutation.UploadedBy(); ok {
		_spec.SetField(tenderdocument.FieldUploadedBy, field.TypeUUID, value)
		_node.UploadedBy = value
	}
	if value, ok := tdc.mutation.UploadedAt(); ok {
		_spec.SetField(tenderdocument.FieldUploadedAt, field.TypeTime, value)
		_node.UploadedAt = value
	}
	if nodes := tdc.mutation.TenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenderdocument.TenderTable,
			Columns: []string{tenderdocument.TenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tender.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TenderDocumentCreateBulk is the builder for creating many TenderDocument entities in bulk.
type TenderDocumentCreateBulk struct {
	config
	err      error
	builders []*TenderDocumentCreate
}

// Save creates the TenderDocument entities in the database.
func (tdcb *TenderDocumentCreateBulk) Save(ctx context.Context) ([]*TenderDocument, error) {
	if tdcb.err != nil {
		return nil, tdcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tdcb.builders))
	nodes := make([]*TenderDocument, len(tdcb.builders))
	mutators := make([]Mutator, len(tdcb.builders))
	for i := range tdcb.builders {
		func(i int, root context.Context) {
			builder := tdcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TenderDocumentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tdcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tdcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tdcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tdcb *TenderDocumentCreateBulk) SaveX(ctx context.Context) []*TenderDocument {
	v, err := tdcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tdcb *TenderDocumentCreateBulk) Exec(ctx context.Context) error {
	_, err := tdcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tdcb *TenderDocumentCreateBulk) ExecX(ctx context.Context) {
	if err := tdcb.Exec(ctx); err != nil {
		panic(err)
	}
}
