// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/projects-service/internal/ent/predicate"
	"github.com/bengobox/projects-service/internal/ent/tender"
	"github.com/bengobox/projects-service/internal/ent/tendercommittee"
	"github.com/bengobox/projects-service/internal/ent/tenderdocument"
	"github.com/bengobox/projects-service/internal/ent/tenderevaluation"
	"github.com/bengobox/projects-service/internal/ent/tendermeeting"
	"github.com/google/uuid"
)

// TenderQuery is the builder for querying Tender entities.
type TenderQuery struct {
	config
	ctx             *QueryContext
	order           []tender.OrderOption
	inters          []Interceptor
	predicates      []predicate.Tender
	withDocuments   *TenderDocumentQuery
	withCommittees  *TenderCommitteeQuery
	withEvaluations *TenderEvaluationQuery
	withMeetings    *TenderMeetingQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TenderQuery builder.
func (tq *TenderQuery) Where(ps ...predicate.Tender) *TenderQuery {
	tq.predicates = append(tq.predicates, ps...)
	return tq
}

// Limit the number of records to be returned by this query.
func (tq *TenderQuery) Limit(limit int) *TenderQuery {
	tq.ctx.Limit = &limit
	return tq
}

// Offset to start from.
func (tq *TenderQuery) Offset(offset int) *TenderQuery {
	tq.ctx.Offset = &offset
	return tq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tq *TenderQuery) Unique(unique bool) *TenderQuery {
	tq.ctx.Unique = &unique
	return tq
}

// Order specifies how the records should be ordered.
func (tq *TenderQuery) Order(o ...tender.OrderOption) *TenderQuery {
	tq.order = append(tq.order, o...)
	return tq
}

// QueryDocuments chains the current query on the "documents" edge.
func (tq *TenderQuery) QueryDocuments() *TenderDocumentQuery {
	query := (&TenderDocumentClient{config: tq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tender.Table, tender.FieldID, selector),
			sqlgraph.To(tenderdocument.Table, tenderdocument.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tender.DocumentsTable, tender.DocumentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCommittees chains the current query on the "committees" edge.
func (tq *TenderQuery) QueryCommittees() *TenderCommitteeQuery {
	query := (&TenderCommitteeClient{config: tq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tender.Table, tender.FieldID, selector),
			sqlgraph.To(tendercommittee.Table, tendercommittee.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tender.CommitteesTable, tender.CommitteesColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEvaluations chains the current query on the "evaluations" edge.
func (tq *TenderQuery) QueryEvaluations() *TenderEvaluationQuery {
	query := (&TenderEvaluationClient{config: tq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tender.Table, tender.FieldID, selector),
			sqlgraph.To(tenderevaluation.Table, tenderevaluation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tender.EvaluationsTable, tender.EvaluationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMeetings chains the current query on the "meetings" edge.
func (tq *TenderQuery) QueryMeetings() *TenderMeetingQuery {
	query := (&TenderMeetingClient{config: tq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tender.Table, tender.FieldID, selector),
			sqlgraph.To(tendermeeting.Table, tendermeeting.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tender.MeetingsTable, tender.MeetingsColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Tender entity from the query.
// Returns a *NotFoundError when no Tender was found.
func (tq *TenderQuery) First(ctx context.Context) (*Tender, error) {
	nodes, err := tq.Limit(1).All(setContextOp(ctx, tq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tender.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tq *TenderQuery) FirstX(ctx context.Context) *Tender {
	node, err := tq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Tender ID from the query.
// Returns a *NotFoundError when no Tender ID was found.
func (tq *TenderQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tq.Limit(1).IDs(setContextOp(ctx, tq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tender.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tq *TenderQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := tq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Tender entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Tender entity is found.
// Returns a *NotFoundError when no Tender entities are found.
func (tq *TenderQuery) Only(ctx context.Context) (*Tender, error) {
	nodes, err := tq.Limit(2).All(setContextOp(ctx, tq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tender.Label}
	default:
		return nil, &NotSingularError{tender.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tq *TenderQuery) OnlyX(ctx context.Context) *Tender {
	node, err := tq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Tender ID in the query.
// Returns a *NotSingularError when more than one Tender ID is found.
// Returns a *NotFoundError when no entities are found.
func (tq *TenderQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tq.Limit(2).IDs(setContextOp(ctx, tq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tender.Label}
	default:
		err = &NotSingularError{tender.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tq *TenderQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := tq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Tenders.
func (tq *TenderQuery) All(ctx context.Context) ([]*Tender, error) {
	ctx = setContextOp(ctx, tq.ctx, "All")
	if err := tq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Tender, *TenderQuery]()
	return withInterceptors[[]*Tender](ctx, tq, qr, tq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tq *TenderQuery) AllX(ctx context.Context) []*Tender {
	nodes, err := tq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Tender IDs.
func (tq *TenderQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if tq.ctx.Unique == nil && tq.path != nil {
		tq.Unique(true)
	}
	ctx = setContextOp(ctx, tq.ctx, "IDs")
	if err = tq.Select(tender.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tq *TenderQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := tq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tq *TenderQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tq.ctx, "Count")
	if err := tq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tq, querierCount[*TenderQuery](), tq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tq *TenderQuery) CountX(ctx context.Context) int {
	count, err := tq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tq *TenderQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tq.ctx, "Exist")
	switch _, err := tq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tq *TenderQuery) ExistX(ctx context.Context) bool {
	exist, err := tq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TenderQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tq *TenderQuery) Clone() *TenderQuery {
	if tq == nil {
		return nil
	}
	return &TenderQuery{
		config:          tq.config,
		ctx:             tq.ctx.Clone(),
		order:           append([]tender.OrderOption{}, tq.order...),
		inters:          append([]Interceptor{}, tq.inters...),
		predicates:      append([]predicate.Tender{}, tq.predicates...),
		withDocuments:   tq.withDocuments.Clone(),
		withCommittees:  tq.withCommittees.Clone(),
		withEvaluations: tq.withEvaluations.Clone(),
		withMeetings:    tq.withMeetings.Clone(),
		// clone intermediate query.
		sql:  tq.sql.Clone(),
		path: tq.path,
	}
}

// WithDocuments tells the query-builder to eager-load the nodes that are connected to
// the "documents" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TenderQuery) WithDocuments(opts ...func(*TenderDocumentQuery)) *TenderQuery {
	query := (&TenderDocumentClient{config: tq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tq.withDocuments = query
	return tq
}

// WithCommittees tells the query-builder to eager-load the nodes that are connected to
// the "committees" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TenderQuery) WithCommittees(opts ...func(*TenderCommitteeQuery)) *TenderQuery {
	query := (&TenderCommitteeClient{config: tq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tq.withCommittees = query
	return tq
}

// WithEvaluations tells the query-builder to eager-load the nodes that are connected to
// the "evaluations" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TenderQuery) WithEvaluations(opts ...func(*TenderEvaluationQuery)) *TenderQuery {
	query := (&TenderEvaluationClient{config: tq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tq.withEvaluations = query
	return tq
}

// WithMeetings tells the query-builder to eager-load the nodes that are connected to
// the "meetings" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TenderQuery) WithMeetings(opts ...func(*TenderMeetingQuery)) *TenderQuery {
	query := (&TenderMeetingClient{config: tq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tq.withMeetings = query
	return tq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID uuid.UUID `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Tender.Query().
//		GroupBy(tender.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tq *TenderQuery) GroupBy(field string, fields ...string) *TenderGroupBy {
	tq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TenderGroupBy{build: tq}
	grbuild.flds = &tq.ctx.Fields
	grbuild.label = tender.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID uuid.UUID `json:"tenant_id,omitempty"`
//	}
//
//	client.Tender.Query().
//		Select(tender.FieldTenantID).
//		Scan(ctx, &v)
func (tq *TenderQuery) Select(fields ...string) *TenderSelect {
	tq.ctx.Fields = append(tq.ctx.Fields, fields...)
	sbuild := &TenderSelect{TenderQuery: tq}
	sbuild.label = tender.Label
	sbuild.flds, sbuild.scan = &tq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TenderSelect configured with the given aggregations.
func (tq *TenderQuery) Aggregate(fns ...AggregateFunc) *TenderSelect {
	return tq.Select().Aggregate(fns...)
}

func (tq *TenderQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tq); err != nil {
				return err
			}
		}
	}
	for _, f := range tq.ctx.Fields {
		if !tender.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tq.path != nil {
		prev, err := tq.path(ctx)
		if err != nil {
			return err
		}
		tq.sql = prev
	}
	return nil
}

func (tq *TenderQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Tender, error) {
	var (
		nodes       = []*Tender{}
		_spec       = tq.querySpec()
		loadedTypes = [4]bool{
			tq.withDocuments != nil,
			tq.withCommittees != nil,
			tq.withEvaluations != nil,
			tq.withMeetings != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Tender).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Tender{config: tq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tq.withDocuments; query != nil {
		if err := tq.loadDocuments(ctx, query, nodes,
			func(n *Tender) { n.Edges.Documents = []*TenderDocument{} },
			func(n *Tender, e *TenderDocument) { n.Edges.Documents = append(n.Edges.Documents, e) }); err != nil {
			return nil, err
		}
	}
	if query := tq.withCommittees; query != nil {
		if err := tq.loadCommittees(ctx, query, nodes,
			func(n *Tender) { n.Edges.Committees = []*TenderCommittee{} },
			func(n *Tender, e *TenderCommittee) { n.Edges.Committees = append(n.Edges.Committees, e) }); err != nil {
			return nil, err
		}
	}
	if query := tq.withEvaluations; query != nil {
		if err := tq.loadEvaluations(ctx, query, nodes,
			func(n *Tender) { n.Edges.Evaluations = []*TenderEvaluation{} },
			func(n *Tender, e *TenderEvaluation) { n.Edges.Evaluations = append(n.Edges.Evaluations, e) }); err != nil {
			return nil, err
		}
	}
	if query := tq.withMeetings; query != nil {
		if err := tq.loadMeetings(ctx, query, nodes,
			func(n *Tender) { n.Edges.Meetings = []*TenderMeeting{} },
			func(n *Tender, e *TenderMeeting) { n.Edges.Meetings = append(n.Edges.Meetings, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tq *TenderQuery) loadDocuments(ctx context.Context, query *TenderDocumentQuery, nodes []*Tender, init func(*Tender), assign func(*Tender, *TenderDocument)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Tender)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(tenderdocument.FieldTenderID)
	}
	query.Where(predicate.TenderDocument(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tender.DocumentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenderID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tender_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (tq *TenderQuery) loadCommittees(ctx context.Context, query *TenderCommitteeQuery, nodes []*Tender, init func(*Tender), assign func(*Tender, *TenderCommittee)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Tender)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(tendercommittee.FieldTenderID)
	}
	query.Where(predicate.TenderCommittee(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tender.CommitteesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenderID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tender_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (tq *TenderQuery) loadEvaluations(ctx context.Context, query *TenderEvaluationQuery, nodes []*Tender, init func(*Tender), assign func(*Tender, *TenderEvaluation)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Tender)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(tenderevaluation.FieldTenderID)
	}
	query.Where(predicate.TenderEvaluation(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tender.EvaluationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenderID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tender_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (tq *TenderQuery) loadMeetings(ctx context.Context, query *TenderMeetingQuery, nodes []*Tender, init func(*Tender), assign func(*Tender, *TenderMeeting)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Tender)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(tendermeeting.FieldTenderID)
	}
	query.Where(predicate.TenderMeeting(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tender.MeetingsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.TenderID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tender_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (tq *TenderQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tq.querySpec()
	_spec.Node.Columns = tq.ctx.Fields
	if len(tq.ctx.Fields) > 0 {
		_spec.Unique = tq.ctx.Unique != nil && *tq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tq.driver, _spec)
}

func (tq *TenderQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tender.Table, tender.Columns, sqlgraph.NewFieldSpec(tender.FieldID, field.TypeUUID))
	_spec.From = tq.sql
	if unique := tq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tq.path != nil {
		_spec.Unique = true
	}
	if fields := tq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tender.FieldID)
		for i := range fields {
			if fields[i] != tender.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tq *TenderQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tq.driver.Dialect())
	t1 := builder.Table(tender.Table)
	columns := tq.ctx.Fields
	if len(columns) == 0 {
		columns = tender.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tq.sql != nil {
		selector = tq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tq.ctx.Unique != nil && *tq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tq.predicates {
		p(selector)
	}
	for _, p := range tq.order {
		p(selector)
	}
	if offset := tq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TenderGroupBy is the group-by builder for Tender entities.
type TenderGroupBy struct {
	selector
	build *TenderQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tgb *TenderGroupBy) Aggregate(fns ...AggregateFunc) *TenderGroupBy {
	tgb.fns = append(tgb.fns, fns...)
	return tgb
}

// Scan applies the selector query and scans the result into the given value.
func (tgb *TenderGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tgb.build.ctx, "GroupBy")
	if err := tgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TenderQuery, *TenderGroupBy](ctx, tgb.build, tgb, tgb.build.inters, v)
}

func (tgb *TenderGroupBy) sqlScan(ctx context.Context, root *TenderQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tgb.fns))
	for _, fn := range tgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tgb.flds)+len(tgb.fns))
		for _, f := range *tgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TenderSelect is the builder for selecting fields of Tender entities.
type TenderSelect struct {
	*TenderQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ts *TenderSelect) Aggregate(fns ...AggregateFunc) *TenderSelect {
	ts.fns = append(ts.fns, fns...)
	return ts
}

// Scan applies the selector query and scans the result into the given value.
func (ts *TenderSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ts.ctx, "Select")
	if err := ts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TenderQuery, *TenderSelect](ctx, ts.TenderQuery, ts, ts.inters, v)
}

func (ts *TenderSelect) sqlScan(ctx context.Context, root *TenderQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ts.fns))
	for _, fn := range ts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
