// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/projects-service/internal/ent/predicate"
	"github.com/bengobox/projects-service/internal/ent/tender"
	"github.com/bengobox/projects-service/internal/ent/tendersubmission"
	"github.com/google/uuid"
)

// TenderSubmissionQuery is the builder for querying TenderSubmission entities.
type TenderSubmissionQuery struct {
	config
	ctx        *QueryContext
	order      []tendersubmission.OrderOption
	inters     []Interceptor
	predicates []predicate.TenderSubmission
	withTender *TenderQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TenderSubmissionQuery builder.
func (tsq *TenderSubmissionQuery) Where(ps ...predicate.TenderSubmission) *TenderSubmissionQuery {
	tsq.predicates = append(tsq.predicates, ps...)
	return tsq
}

// Limit the number of records to be returned by this query.
func (tsq *TenderSubmissionQuery) Limit(limit int) *TenderSubmissionQuery {
	tsq.ctx.Limit = &limit
	return tsq
}

// Offset to start from.
func (tsq *TenderSubmissionQuery) Offset(offset int) *TenderSubmissionQuery {
	tsq.ctx.Offset = &offset
	return tsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tsq *TenderSubmissionQuery) Unique(unique bool) *TenderSubmissionQuery {
	tsq.ctx.Unique = &unique
	return tsq
}

// Order specifies how the records should be ordered.
func (tsq *TenderSubmissionQuery) Order(o ...tendersubmission.OrderOption) *TenderSubmissionQuery {
	tsq.order = append(tsq.order, o...)
	return tsq
}

// QueryTender chains the current query on the "tender" edge.
func (tsq *TenderSubmissionQuery) QueryTender() *TenderQuery {
	query := (&TenderClient{config: tsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tendersubmission.Table, tendersubmission.FieldID, selector),
			sqlgraph.To(tender.Table, tender.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, tendersubmission.TenderTable, tendersubmission.TenderColumn),
		)
		fromU = sqlgraph.SetNeighbors(tsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TenderSubmission entity from the query.
// Returns a *NotFoundError when no TenderSubmission was found.
func (tsq *TenderSubmissionQuery) First(ctx context.Context) (*TenderSubmission, error) {
	nodes, err := tsq.Limit(1).All(setContextOp(ctx, tsq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tendersubmission.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tsq *TenderSubmissionQuery) FirstX(ctx context.Context) *TenderSubmission {
	node, err := tsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TenderSubmission ID from the query.
// Returns a *NotFoundError when no TenderSubmission ID was found.
func (tsq *TenderSubmissionQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tsq.Limit(1).IDs(setContextOp(ctx, tsq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tendersubmission.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tsq *TenderSubmissionQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := tsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TenderSubmission entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TenderSubmission entity is found.
// Returns a *NotFoundError when no TenderSubmission entities are found.
func (tsq *TenderSubmissionQuery) Only(ctx context.Context) (*TenderSubmission, error) {
	nodes, err := tsq.Limit(2).All(setContextOp(ctx, tsq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tendersubmission.Label}
	default:
		return nil, &NotSingularError{tendersubmission.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tsq *TenderSubmissionQuery) OnlyX(ctx context.Context) *TenderSubmission {
	node, err := tsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TenderSubmission ID in the query.
// Returns a *NotSingularError when more than one TenderSubmission ID is found.
// Returns a *NotFoundError when no entities are found.
func (tsq *TenderSubmissionQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tsq.Limit(2).IDs(setContextOp(ctx, tsq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tendersubmission.Label}
	default:
		err = &NotSingularError{tendersubmission.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tsq *TenderSubmissionQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := tsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TenderSubmissions.
func (tsq *TenderSubmissionQuery) All(ctx context.Context) ([]*TenderSubmission, error) {
	ctx = setContextOp(ctx, tsq.ctx, "All")
	if err := tsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TenderSubmission, *TenderSubmissionQuery]()
	return withInterceptors[[]*TenderSubmission](ctx, tsq, qr, tsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tsq *TenderSubmissionQuery) AllX(ctx context.Context) []*TenderSubmission {
	nodes, err := tsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TenderSubmission IDs.
func (tsq *TenderSubmissionQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if tsq.ctx.Unique == nil && tsq.path != nil {
		tsq.Unique(true)
	}
	ctx = setContextOp(ctx, tsq.ctx, "IDs")
	if err = tsq.Select(tendersubmission.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tsq *TenderSubmissionQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := tsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tsq *TenderSubmissionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tsq.ctx, "Count")
	if err := tsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tsq, querierCount[*TenderSubmissionQuery](), tsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tsq *TenderSubmissionQuery) CountX(ctx context.Context) int {
	count, err := tsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tsq *TenderSubmissionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tsq.ctx, "Exist")
	switch _, err := tsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tsq *TenderSubmissionQuery) ExistX(ctx context.Context) bool {
	exist, err := tsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TenderSubmissionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tsq *TenderSubmissionQuery) Clone() *TenderSubmissionQuery {
	if tsq == nil {
		return nil
	}
	return &TenderSubmissionQuery{
		config:     tsq.config,
		ctx:        tsq.ctx.Clone(),
		order:      append([]tendersubmission.OrderOption{}, tsq.order...),
		inters:     append([]Interceptor{}, tsq.inters...),
		predicates: append([]predicate.TenderSubmission{}, tsq.predicates...),
		withTender: tsq.withTender.Clone(),
		// clone intermediate query.
		sql:  tsq.sql.Clone(),
		path: tsq.path,
	}
}

// WithTender tells the query-builder to eager-load the nodes that are connected to
// the "tender" edge. The optional arguments are used to configure the query builder of the edge.
func (tsq *TenderSubmissionQuery) WithTender(opts ...func(*TenderQuery)) *TenderSubmissionQuery {
	query := (&TenderClient{config: tsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tsq.withTender = query
	return tsq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID uuid.UUID `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TenderSubmission.Query().
//		GroupBy(tendersubmission.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tsq *TenderSubmissionQuery) GroupBy(field string, fields ...string) *TenderSubmissionGroupBy {
	tsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TenderSubmissionGroupBy{build: tsq}
	grbuild.flds = &tsq.ctx.Fields
	grbuild.label = tendersubmission.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID uuid.UUID `json:"tenant_id,omitempty"`
//	}
//
//	client.TenderSubmission.Query().
//		Select(tendersubmission.FieldTenantID).
//		Scan(ctx, &v)
func (tsq *TenderSubmissionQuery) Select(fields ...string) *TenderSubmissionSelect {
	tsq.ctx.Fields = append(tsq.ctx.Fields, fields...)
	sbuild := &TenderSubmissionSelect{TenderSubmissionQuery: tsq}
	sbuild.label = tendersubmission.Label
	sbuild.flds, sbuild.scan = &tsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TenderSubmissionSelect configured with the given aggregations.
func (tsq *TenderSubmissionQuery) Aggregate(fns ...AggregateFunc) *TenderSubmissionSelect {
	return tsq.Select().Aggregate(fns...)
}

func (tsq *TenderSubmissionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tsq); err != nil {
				return err
			}
		}
	}
	for _, f := range tsq.ctx.Fields {
		if !tendersubmission.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tsq.path != nil {
		prev, err := tsq.path(ctx)
		if err != nil {
			return err
		}
		tsq.sql = prev
	}
	return nil
}

func (tsq *TenderSubmissionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TenderSubmission, error) {
	var (
		nodes       = []*TenderSubmission{}
		_spec       = tsq.querySpec()
		loadedTypes = [1]bool{
			tsq.withTender != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TenderSubmission).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TenderSubmission{config: tsq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tsq.withTender; query != nil {
		if err := tsq.loadTender(ctx, query, nodes, nil,
			func(n *TenderSubmission, e *Tender) { n.Edges.Tender = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tsq *TenderSubmissionQuery) loadTender(ctx context.Context, query *TenderQuery, nodes []*TenderSubmission, init func(*TenderSubmission), assign func(*TenderSubmission, *Tender)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*TenderSubmission)
	for i := range nodes {
		fk := nodes[i].TenderID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tender.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "tender_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tsq *TenderSubmissionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tsq.querySpec()
	_spec.Node.Columns = tsq.ctx.Fields
	if len(tsq.ctx.Fields) > 0 {
		_spec.Unique = tsq.ctx.Unique != nil && *tsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tsq.driver, _spec)
}

func (tsq *TenderSubmissionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tendersubmission.Table, tendersubmission.Columns, sqlgraph.NewFieldSpec(tendersubmission.FieldID, field.TypeUUID))
	_spec.From = tsq.sql
	if unique := tsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tsq.path != nil {
		_spec.Unique = true
	}
	if fields := tsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tendersubmission.FieldID)
		for i := range fields {
			if fields[i] != tendersubmission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if tsq.withTender != nil {
			_spec.Node.AddColumnOnce(tendersubmission.FieldTenderID)
		}
	}
	if ps := tsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tsq *TenderSubmissionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tsq.driver.Dialect())
	t1 := builder.Table(tendersubmission.Table)
	columns := tsq.ctx.Fields
	if len(columns) == 0 {
		columns = tendersubmission.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tsq.sql != nil {
		selector = tsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tsq.ctx.Unique != nil && *tsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tsq.predicates {
		p(selector)
	}
	for _, p := range tsq.order {
		p(selector)
	}
	if offset := tsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TenderSubmissionGroupBy is the group-by builder for TenderSubmission entities.
type TenderSubmissionGroupBy struct {
	selector
	build *TenderSubmissionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tsgb *TenderSubmissionGroupBy) Aggregate(fns ...AggregateFunc) *TenderSubmissionGroupBy {
	tsgb.fns = append(tsgb.fns, fns...)
	return tsgb
}

// Scan applies the selector query and scans the result into the given value.
func (tsgb *TenderSubmissionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tsgb.build.ctx, "GroupBy")
	if err := tsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TenderSubmissionQuery, *TenderSubmissionGroupBy](ctx, tsgb.build, tsgb, tsgb.build.inters, v)
}

func (tsgb *TenderSubmissionGroupBy) sqlScan(ctx context.Context, root *TenderSubmissionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tsgb.fns))
	for _, fn := range tsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tsgb.flds)+len(tsgb.fns))
		for _, f := range *tsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TenderSubmissionSelect is the builder for selecting fields of TenderSubmission entities.
type TenderSubmissionSelect struct {
	*TenderSubmissionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tss *TenderSubmissionSelect) Aggregate(fns ...AggregateFunc) *TenderSubmissionSelect {
	tss.fns = append(tss.fns, fns...)
	return tss
}

// Scan applies the selector query and scans the result into the given value.
func (tss *TenderSubmissionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tss.ctx, "Select")
	if err := tss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TenderSubmissionQuery, *TenderSubmissionSelect](ctx, tss.TenderSubmissionQuery, tss, tss.inters, v)
}

func (tss *TenderSubmissionSelect) sqlScan(ctx context.Context, root *TenderSubmissionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tss.fns))
	for _, fn := range tss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
