// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/projects-service/internal/ent/tendercommittee"
	"github.com/bengobox/projects-service/internal/ent/tendercommitteemember"
	"github.com/google/uuid"
)

// TenderCommitteeMember is the model entity for the TenderCommitteeMember schema.
type TenderCommitteeMember struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CommitteeID holds the value of the "committee_id" field.
	CommitteeID uuid.UUID `json:"committee_id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// Role holds the value of the "role" field.
	Role string `json:"role,omitempty"`
	// JoinedAt holds the value of the "joined_at" field.
	JoinedAt time.Time `json:"joined_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TenderCommitteeMemberQuery when eager-loading is set.
	Edges        TenderCommitteeMemberEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TenderCommitteeMemberEdges holds the relations/edges for other nodes in the graph.
type TenderCommitteeMemberEdges struct {
	// Committee holds the value of the committee edge.
	Committee *TenderCommittee `json:"committee,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CommitteeOrErr returns the Committee value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TenderCommitteeMemberEdges) CommitteeOrErr() (*TenderCommittee, error) {
	if e.Committee != nil {
		return e.Committee, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tendercommittee.Label}
	}
	return nil, &NotLoadedError{edge: "committee"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TenderCommitteeMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tendercommitteemember.FieldRole:
			values[i] = new(sql.NullString)
		case tendercommitteemember.FieldJoinedAt:
			values[i] = new(sql.NullTime)
		case tendercommitteemember.FieldID, tendercommitteemember.FieldCommitteeID, tendercommitteemember.FieldTenantID, tendercommitteemember.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TenderCommitteeMember fields.
func (tcm *TenderCommitteeMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tendercommitteemember.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				tcm.ID = *value
			}
		case tendercommitteemember.FieldCommitteeID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field committee_id", values[i])
			} else if value != nil {
				tcm.CommitteeID = *value
			}
		case tendercommitteemember.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				tcm.TenantID = *value
			}
		case tendercommitteemember.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				tcm.UserID = *value
			}
		case tendercommitteemember.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				tcm.Role = value.String
			}
		case tendercommitteemember.FieldJoinedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field joined_at", values[i])
			} else if value.Valid {
				tcm.JoinedAt = value.Time
			}
		default:
			tcm.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TenderCommitteeMember.
// This includes values selected through modifiers, order, etc.
func (tcm *TenderCommitteeMember) Value(name string) (ent.Value, error) {
	return tcm.selectValues.Get(name)
}

// QueryCommittee queries the "committee" edge of the TenderCommitteeMember entity.
func (tcm *TenderCommitteeMember) QueryCommittee() *TenderCommitteeQuery {
	return NewTenderCommitteeMemberClient(tcm.config).QueryCommittee(tcm)
}

// Update returns a builder for updating this TenderCommitteeMember.
// Note that you need to call TenderCommitteeMember.Unwrap() before calling this method if this TenderCommitteeMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (tcm *TenderCommitteeMember) Update() *TenderCommitteeMemberUpdateOne {
	return NewTenderCommitteeMemberClient(tcm.config).UpdateOne(tcm)
}

// Unwrap unwraps the TenderCommitteeMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tcm *TenderCommitteeMember) Unwrap() *TenderCommitteeMember {
	_tx, ok := tcm.config.driver.(*txDriver)
	if !ok {
		panic("ent: TenderCommitteeMember is not a transactional entity")
	}
	tcm.config.driver = _tx.drv
	return tcm
}

// String implements the fmt.Stringer.
func (tcm *TenderCommitteeMember) String() string {
	var builder strings.Builder
	builder.WriteString("TenderCommitteeMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", tcm.ID))
	builder.WriteString("committee_id=")
	builder.WriteString(fmt.Sprintf("%v", tcm.CommitteeID))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", tcm.TenantID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", tcm.UserID))
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(tcm.Role)
	builder.WriteString(", ")
	builder.WriteString("joined_at=")
	builder.WriteString(tcm.JoinedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TenderCommitteeMembers is a parsable slice of TenderCommitteeMember.
type TenderCommitteeMembers []*TenderCommitteeMember
