// Code generated by ent, DO NOT EDIT.

package tenantsyncevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the tenantsyncevent type in the database.
	Label = "tenant_sync_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldTenantSlug holds the string denoting the tenant_slug field in the database.
	FieldTenantSlug = "tenant_slug"
	// FieldSourceService holds the string denoting the source_service field in the database.
	FieldSourceService = "source_service"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldSyncedAt holds the string denoting the synced_at field in the database.
	FieldSyncedAt = "synced_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// Table holds the table name of the tenantsyncevent in the database.
	Table = "tenant_sync_events"
)

// Columns holds all SQL columns for tenantsyncevent fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldTenantSlug,
	FieldSourceService,
	FieldPayload,
	FieldSyncedAt,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TenantSlugValidator is a validator for the "tenant_slug" field. It is called by the builders before save.
	TenantSlugValidator func(string) error
	// SourceServiceValidator is a validator for the "source_service" field. It is called by the builders before save.
	SourceServiceValidator func(string) error
	// DefaultSyncedAt holds the default value on creation for the "synced_at" field.
	DefaultSyncedAt func() time.Time
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the TenantSyncEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByTenantSlug orders the results by the tenant_slug field.
func ByTenantSlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantSlug, opts...).ToFunc()
}

// BySourceService orders the results by the source_service field.
func BySourceService(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceService, opts...).ToFunc()
}

// BySyncedAt orders the results by the synced_at field.
func BySyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncedAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}
