// Code generated by ent, DO NOT EDIT.

package expense

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the expense type in the database.
	Label = "expense"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBudgetID holds the string denoting the budget_id field in the database.
	FieldBudgetID = "budget_id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldIncurredBy holds the string denoting the incurred_by field in the database.
	FieldIncurredBy = "incurred_by"
	// FieldIncurredAt holds the string denoting the incurred_at field in the database.
	FieldIncurredAt = "incurred_at"
	// FieldReceiptURL holds the string denoting the receipt_url field in the database.
	FieldReceiptURL = "receipt_url"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeBudget holds the string denoting the budget edge name in mutations.
	EdgeBudget = "budget"
	// Table holds the table name of the expense in the database.
	Table = "expenses"
	// BudgetTable is the table that holds the budget relation/edge.
	BudgetTable = "expenses"
	// BudgetInverseTable is the table name for the Budget entity.
	// It exists in this package in order to avoid circular dependency with the "budget" package.
	BudgetInverseTable = "budgets"
	// BudgetColumn is the table column denoting the budget relation/edge.
	BudgetColumn = "budget_id"
)

// Columns holds all SQL columns for expense fields.
var Columns = []string{
	FieldID,
	FieldBudgetID,
	FieldProjectID,
	FieldTenantID,
	FieldDescription,
	FieldAmount,
	FieldCurrency,
	FieldCategory,
	FieldIncurredBy,
	FieldIncurredAt,
	FieldReceiptURL,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Expense queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBudgetID orders the results by the budget_id field.
func ByBudgetID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBudgetID, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByIncurredBy orders the results by the incurred_by field.
func ByIncurredBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIncurredBy, opts...).ToFunc()
}

// ByIncurredAt orders the results by the incurred_at field.
func ByIncurredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIncurredAt, opts...).ToFunc()
}

// ByReceiptURL orders the results by the receipt_url field.
func ByReceiptURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReceiptURL, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByBudgetField orders the results by budget field.
func ByBudgetField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBudgetStep(), sql.OrderByField(field, opts...))
	}
}
func newBudgetStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BudgetInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, BudgetTable, BudgetColumn),
	)
}
