// Code generated by ent, DO NOT EDIT.

package timelog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/projects-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldLTE(FieldID, id))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldEQ(FieldProjectID, v))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldEQ(FieldTaskID, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldEQ(FieldTenantID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldEQ(FieldUserID, v))
}

// Hours applies equality check predicate on the "hours" field. It's identical to HoursEQ.
func Hours(v float64) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldEQ(FieldHours, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldEQ(FieldDescription, v))
}

// LoggedDate applies equality check predicate on the "logged_date" field. It's identical to LoggedDateEQ.
func LoggedDate(v time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldEQ(FieldLoggedDate, v))
}

// IsBillable applies equality check predicate on the "is_billable" field. It's identical to IsBillableEQ.
func IsBillable(v bool) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldEQ(FieldIsBillable, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldNotIn(FieldProjectID, vs...))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldNotIn(FieldTaskID, vs...))
}

// TaskIDGT applies the GT predicate on the "task_id" field.
func TaskIDGT(v uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldGT(FieldTaskID, v))
}

// TaskIDGTE applies the GTE predicate on the "task_id" field.
func TaskIDGTE(v uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldGTE(FieldTaskID, v))
}

// TaskIDLT applies the LT predicate on the "task_id" field.
func TaskIDLT(v uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldLT(FieldTaskID, v))
}

// TaskIDLTE applies the LTE predicate on the "task_id" field.
func TaskIDLTE(v uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldLTE(FieldTaskID, v))
}

// TaskIDIsNil applies the IsNil predicate on the "task_id" field.
func TaskIDIsNil() predicate.TimeLog {
	return predicate.TimeLog(sql.FieldIsNull(FieldTaskID))
}

// TaskIDNotNil applies the NotNil predicate on the "task_id" field.
func TaskIDNotNil() predicate.TimeLog {
	return predicate.TimeLog(sql.FieldNotNull(FieldTaskID))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldLTE(FieldTenantID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldLTE(FieldUserID, v))
}

// HoursEQ applies the EQ predicate on the "hours" field.
func HoursEQ(v float64) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldEQ(FieldHours, v))
}

// HoursNEQ applies the NEQ predicate on the "hours" field.
func HoursNEQ(v float64) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldNEQ(FieldHours, v))
}

// HoursIn applies the In predicate on the "hours" field.
func HoursIn(vs ...float64) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldIn(FieldHours, vs...))
}

// HoursNotIn applies the NotIn predicate on the "hours" field.
func HoursNotIn(vs ...float64) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldNotIn(FieldHours, vs...))
}

// HoursGT applies the GT predicate on the "hours" field.
func HoursGT(v float64) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldGT(FieldHours, v))
}

// HoursGTE applies the GTE predicate on the "hours" field.
func HoursGTE(v float64) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldGTE(FieldHours, v))
}

// HoursLT applies the LT predicate on the "hours" field.
func HoursLT(v float64) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldLT(FieldHours, v))
}

// HoursLTE applies the LTE predicate on the "hours" field.
func HoursLTE(v float64) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldLTE(FieldHours, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.TimeLog {
	return predicate.TimeLog(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.TimeLog {
	return predicate.TimeLog(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldContainsFold(FieldDescription, v))
}

// LoggedDateEQ applies the EQ predicate on the "logged_date" field.
func LoggedDateEQ(v time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldEQ(FieldLoggedDate, v))
}

// LoggedDateNEQ applies the NEQ predicate on the "logged_date" field.
func LoggedDateNEQ(v time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldNEQ(FieldLoggedDate, v))
}

// LoggedDateIn applies the In predicate on the "logged_date" field.
func LoggedDateIn(vs ...time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldIn(FieldLoggedDate, vs...))
}

// LoggedDateNotIn applies the NotIn predicate on the "logged_date" field.
func LoggedDateNotIn(vs ...time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldNotIn(FieldLoggedDate, vs...))
}

// LoggedDateGT applies the GT predicate on the "logged_date" field.
func LoggedDateGT(v time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldGT(FieldLoggedDate, v))
}

// LoggedDateGTE applies the GTE predicate on the "logged_date" field.
func LoggedDateGTE(v time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldGTE(FieldLoggedDate, v))
}

// LoggedDateLT applies the LT predicate on the "logged_date" field.
func LoggedDateLT(v time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldLT(FieldLoggedDate, v))
}

// LoggedDateLTE applies the LTE predicate on the "logged_date" field.
func LoggedDateLTE(v time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldLTE(FieldLoggedDate, v))
}

// IsBillableEQ applies the EQ predicate on the "is_billable" field.
func IsBillableEQ(v bool) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldEQ(FieldIsBillable, v))
}

// IsBillableNEQ applies the NEQ predicate on the "is_billable" field.
func IsBillableNEQ(v bool) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldNEQ(FieldIsBillable, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TimeLog {
	return predicate.TimeLog(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.TimeLog {
	return predicate.TimeLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.TimeLog {
	return predicate.TimeLog(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TimeLog) predicate.TimeLog {
	return predicate.TimeLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TimeLog) predicate.TimeLog {
	return predicate.TimeLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TimeLog) predicate.TimeLog {
	return predicate.TimeLog(sql.NotPredicates(p))
}
